compat/win32/git.manifest, git.rc
Just like it is done in https://github.com/git-for-windows/MSYS2-packages/blob/master/git/git-1.9.0-manifest-msys2.patch, we should embed the manifest by default (instead of using external `.manifest` files, as we used to).
That linked patch should be simplified a little bit, e.g. by adding `$(RESOURCE_OBJS)` to `$(GITLIBS)` to avoid touching so many lines at once.
=> Embed a manifest into git.exe

compat/mingw.h
Replace the commit message with this one:
Assorted header fixes to support MSys2-based MinGW build
The excellent MSys2 project brings a substantially updated MinGW
environment including newer GCC versions and new headers. To support
compiling Git, let's special-case the new MinGW (tell-tale: the
_MINGW_MAJOR_MINOR constant is defined).
=> squash! Port header fixes from MSys2

t/t9400-git-cvsserver-server.sh, t/t9401-git-cvsserver-crlf.sh, t/t9402-git-cvsserver-refs.sh
The CVS tests expect `pwd` to return a POSIX-style directory. Let's skip
our MinGW-specific override to let `pwd` output a Windows-style directory
for that reason.
=> mingw: cvs-test-fixes

compat/mingw.c, compat/mingw.h, compat/winansi.c
When we were using `winpty`, the `git log` command called the pager correctly. However, without using `winpty` this is not the case. Most likely, there is a way to teach the `msys2-runtime` to special-case `git.exe` and pass the tty through so that Git knows that it is running inside a console.
Note: this is only an issue when not running in `cmd.exe`. However, we want to switch to a nicer terminal in the upcoming Git for Windows release.
=> Teach msys2-runtime to hand the tty through to Git

git-gui/git-gui.sh
If we use 'eval exec $opt $cmdp $args' to execute git command,
tcl engine will convert the output of the git comand with the rule
system default code page to unicode.
But cp936 -> unicode conversion implicitly done by exec is not reversible.
So we have to use git_read instead.
Bug report and an original reproducer by Cloud Chou:
https://github.com/msysgit/git/issues/302
Karsten Blees writes this code patch.
Cloud Chou find the reason of the bug.
Thanks-to: dscho
Thanks-to: patthoyts
Signed-off-by: Karsten Blees <blees@dcon.de>
Original-test-by: Cloud Chou <515312382@qq.com>
Signed-off-by: Cloud Chou <515312382@qq.com>
=> git-gui:handle the encoding of Git's output correctly

Makefile, compat/win32/git-wrapper.c, config.mak.uname
We cannot rely on hardlinks to keep disk usage low when installing the builtins into `libexec/`. Therefore, we need something very small we can use instead for backwards-compatibility.
The [Git wrapper established in msysGit](https://github.com/msysgit/msysgit/tree/master/src/git-wrapper) is ideal for that: it is already an executable users can call instead of Git (its original purpose is to call Git from `cmd.exe` without the need to call a script setting up the environment correctly). We can easily extend it to serve another purpose, too.
=> Use msysGit's `git-wrapper` instead of the builtins

config.mak.uname
This fixes the MSYS1-based build which otherwise would have the variables
but not the build targets.
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
=> mingw: Define git-wrapper variables in the scope of the build targets

compat/terminal.c
The `git_terminal_prompt` calls with `xterm`, specially with `mintty` can
not rely on the `WIN32` console. The `MSYS_TTY_HANDLES` should be used to
open the proper console input and output streams.
Signed-off-by: nalla <nalla@hamal.uberspace.de>
=> mingw: Proper `git_terminal_prompt` with `xterm`

compat/mingw.c
Wow. This has really taken quite a lot of time to debug. This developer alone spent 15 hours tracking it down and squashing it, and @nalla as well as @sschuberth helped as well.
=> Fix access violations when cloning/fetching via HTTPS

compat/win32/git-wrapper.c
The original purpose of the Git wrapper is to run from inside Git for
Windows' /cmd/ directory, to allow setting up some environment variables
before Git is allowed to take over.
Due to differences in the file system layout, MSys2 requires some
changes for that to work.
=> git-wrapper: support MSys2

compat/win32/git-wrapper.c
When *Git for Windows* is installed into a directory that has spaces in
it, e.g. `C:\Program Files\Git`, the `git-wrapper` appends this directory
unquoted when fixing up the command line. To resolve this, just quote the
provided `execpath`.
This commit *should* fix https://github.com/git-for-windows/git/issues/51.
@kevin-david Maybe you could give it a try?
Signed-off-by: nalla <nalla@hamal.uberspace.de>
=> git-wrapper: support git.exe to be in a spaced dir

compat/regex/regcomp.c
[5621f24 broke the MSYS1 build](https://dscho.cloudapp.net/job/gfw-msys1-build-git/40/console) due to a missing typedef for `intptr_t`, so fix it again by including the required MSYS1 header file. Although not required for MSYS2, that header exists there, too, and unconditionally including it should have no negative impact.
=> fixup! Silence GCC's "cast of pointer to integer of a different size" warning

gettext.c
=> gettext: always use UTF-8 on native Windows

compat/mingw.c, compat/win32/git-wrapper.c
This fixes several issues that recently crept into git's environment code.
=> RFC: Diverse environment fixes

Documentation/Makefile, Documentation/giteveryday.txt, Documentation/user-manual.txt
This PR for issue #79 prepares the documentation do be built by `asciidoctor`.
The documentation can be built by the following call.
```bash
make doc ASCIIDOC=asciidoctor ASCIIDOC_HTML=html5 ASCIIDOC_DOCBOOK=docbook45 ASCIIDOC_EXTRA="'-alitdd=&#45;&#45;'" ASCIIDOC_CONF='-I/mingw64/lib/asciidoctor-extensions -rman-inline-macro'
```
Note: use `ASCIIDOC_CONF='-I/mingw32/lib/asciidoctor-extensions -rman-inline-macro'` on `32bit`.
You need to have the [asciidoctor-extensions](https://github.com/git-for-windows/MINGW-packages/tree/master/mingw-w64-asciidoctor-extensions) package installed.
=> Asciidoctor fixes

builtin/clean.c
For performance reasons `stdout` is not unbuffered by default. That leads
to problems if after printing to `stdout` a read on `stdin` is performed.
For that reason interactive commands like `git clean -i` do not function
properly anymore if the `stdout` is not flushed by `fflush(stdout)` before
trying to read from `stdin`.
In the case of `git clean -i` all reads on `stdin` were preceded by a
`fflush(stdout)` call.
This fixes #97.
=> mingw: explicitly `fflush` stdout

compat/mingw.c, compat/mingw.h, compat/winansi.c, config.mak.uname
This fixes issue #85 and part of issue #74
=> Better MSys PTY detection

builtin/gc.c, compat/mingw.h, git-compat-util.h
Signed-off-by: Waldek Maleska <w.maleska@gmail.com>
=> Correct fscanf formatting string for I64u values

Documentation/config.txt, compat/mingw.c, compat/mingw.h, config.c, git-compat-util.h
As discussed in https://github.com/libgit2/libgit2/pull/3040, the Windows-based Git projects (both Git for Windows and libgit2) would like to share configuration. It was determined that the best (and most "Windows") way is to have the system-wide configuration in `%PROGRAMDATA%\Git\config`.
This requires three changes in Git for Windows:
- we need to read from that location first, before looking in `etc/gitconfig` and the rest
- we need to update the documentation to state that new behavior
- we need to teach the installer to copy over existing `etc/gitconfig` from Git for Windows 1.x setups
=> Add support for %PROGRAMDATA%\Git\config

compat/mingw.c
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
=> windows_wide_config: Fix wbuffer to be of the wchar_t type

README.md
After publishing the governance model on the [developer
page](http://git-for-windows.github.io), lets add a link on the
`README.md` too.
Signed-off-by: 마누엘 <nalla@hamal.uberspace.de>
=> readme: added link to governance model

compat/terminal.c
During the next rebase merge the clarification of the *read from the
console* command with the previous commits. Then get rid of this commit
message.
Signed-off-by: 마누엘 <nalla@hamal.uberspace.de>
=> fixup! mingw: Support `git_terminal_prompt` with more terminals

builtin/blame.c, t/t8003-blame-corner-cases.sh
A typical setup under Windows is to set core.eol to CRLF, and text
files are marked as "text" in .gitattributes, or core.autocrlf is
set to true.
After 4d4813a5 "git blame" no longer works as expected for such a
set-up.  Every line is annotated as "Not Committed Yet", even though
the working directory is clean.  This is because the commit removed
the conversion in blame.c for all files, with or without CRLF in the
repo.
Having files with CRLF in the repo and core.autocrlf=input is a
temporary situation, and the files, if committed as is, will be
normalized in the repo, which _will_ be a notable change.  Blaming
them with "Not Committed Yet" is the right result.  Revert commit
4d4813a5 which was a misguided attempt to "solve" a non-problem.
Add two test cases in t8003 to verify the correct …
=> blame: CRLF in the working tree and LF in the repo

compat/win32/git-wrapper.c
=> git-wrapper: don't set the console input code page

compat/terminal.c
Followup to #74 mintty issues / @dscho's d56d2f8
* Fixes a few minor issues with `git_terminal_prompt` (see individual fixup commits)
* Use `read -s` instead of `stty echo` (for fewer processes and MSys1 compatibility)
* ~~Drop CONIN$ / CONOUT$ in favor of the shell based solution (for Unicode support)~~ see discussion
* ~~Drop unnecessary `SetConsoleCP()` from git-wrapper~~ see PR #142
Tested with git-bash, git-cmd, bash in native console, and MSys1 bash (with compat/terminal.c backported to msysgit/git/master).
=> git_terminal_prompt fixes and Unicode support

compat/mingw.c, compat/mingw.h, compat/win32.h, compat/win32/dirent.c, compat/win32/fscache.c, compat/winansi.c, lockfile.c, strbuf.c, t/t7800-difftool.sh, t/t9100-git-svn-basic.sh
This with https://github.com/git-for-windows/msys2-runtime/pull/10 should fix issue #117
I only tested this as admin with UAC disabled, so feedback from end users with UAC is welcome.
Design goals:
* Symlinks should be disabled by default (due to the many quirks with Windows symlinks such as permissions, UAC, D/F conflicts, '..' path resolution etc.).
* Existing functionality should not be affected if symlinks are disabled (i.e. guard symlink-specific code with `if (has_symlinks)`).
* Minimize changes to core git code and the test suite.
* Don't try to resolve symlinks manually (i.e. let Windows do the job by opening the symlink and using `Get*ByHandle()`).
To run the test-suite with symlinks enabled:
```
export MSYS=winsymlinks:nativestrict
make test # or prove...
```
=> Symlink support

compat/mingw.c
In contrast to MSYS2, MSYS1 not only defines REPARSE_DATA_BUFFER in
"ntifs.h" but also in "winnt.h". Luckily, we can distinguish between
MSYS1's and MSYS2's "winnt.h" by looking at the include-guards:
While MSYS1 defines "_WINNT_H", MSYS2 defines "_WINNT_".
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
=> mingw: Fix the MSYS1 build

t/t0027-auto-crlf.sh
Update t0027 with upstream Git
=> 150630 git for windows update t0027

Vagrantfile
This is Ubuntu Trusty now. As that is obvious from the code remove the
comment completely.
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
=> Vagrantfile: Remove the comment about Ubuntu Precise

compat/mingw.c
The contact for the stat() and lstat() function is:
> stat() stats the file pointed to by path and fills in buf.
> lstat() is identical to stat(), except that if path is a symbolic link, then the link itself is stat-ed, not the file that it refers to.
stat() should always return the statistics of the file or directory a symbolic link is pointing to. The lstat() function is used to get the stats for the symlink. Hence the check should not be there.
=> The stat() method should not be dependent on the core.symlinks config entry

perl/Git/SVN.pm
=> Verify memoized files can be reloaded before using them

CONTRIBUTING.md
It is better to state clearly expectations and intentions than to assume quietly that everybody agrees.
So let's add a concise section to the governance model, maybe modeled after http://software-carpentry.org/conduct.html.
=> Add a brief "code of conduct" section to the Governance Model

attr.c
On Windows, a file name containing a colon is illegal. We should
therefore expect the corresponding errno when `fopen()` is called for a
path of the form <commit>:.gitattributes.
This fixes https://github.com/git-for-windows/git/issues/255.
=> mingw: Suppress warning that <commit>:.gitattributes does not exist

compat/winansi.c
Git only colours the output and uses pagination if isatty() returns 1.  MSys and Cygwin emulate pseudo terminals via named pipes, meaning that isatty() returns 0.
Commit 3adef8de5513390459e1caa999e7774adb89a44d fixed this for MSys terminals, but not Cygwin.
The named pipes that Cygwin and Msys use are very similar.  MSys PTY pipes are called 'msys-*-pty*' and Cygwin uses 'cygwin-*-pty*'.  This commit modifies the existing check to allow both MSys and Cygwin PTY pipes to be identified as TTYs.
Note that Pagination is still broken on Cygwin.  less.exe is spawned (as seen in Process Explorer and using GIT_TRACE=1), but the output is not being piped into it.
This partially fixes https://github.com/git-for-windows/git/issues/267
=> winansi.c: Fix colourization on Cygwin pseudo terminals.

compat/mingw.h, git-compat-util.h, path.c
It has been reported that `git.exe` won't be able to access alternates when they are specified as UNC paths. Let's make that work.
=> Make alternates work on UNC paths

git-add--interactive.perl, t/t3701-add-interactive.sh
This fixes https://github.com/msysgit/git/issues/182.
Inspired by Pull Request 218 using code from @PhilipDavis.
=> Allow `add -p` and `add -i` with a large number of files

compat/mingw.c, compat/mingw.h, compat/win32/fscache.c, config.mak.uname
Here are the nanosecond file time patches, rebased to v2.5.3.
While testing, I found a few nasty issues when using git variants with different file time resolutions on the same repository (e.g. Git for Windows and JGit/EGit) [1]. This is why the second patch does *not* currently enable USE_NSEC in the Makefile (use ```make USE_NSEC=1``` to build with nanosecond support).
[1] http://article.gmane.org/gmane.comp.version-control.git/278683
=> nanosecond file times for v2.5.3

compat/win32mmap.c
Kevin David provided access to his VM where a simple `git fetch` would produce this error output:
```
fatal: mmap failed: No error
fatal: write error: Invalid argument
```
The reason was that several bits of our `mmap()` emulation left room for improvement. This Pull Request tries to close the gap.
=> Better mmap() emulation

compat/mingw.c, compat/mingw.h, git-compat-util.h, ident.c
The concept of using `getpwuid()` is slightly incompatible with the design of the related functions in the Win32 API. While it *does* have a way to provide the user's display name (which is called "gecos"), there is no POSIX function to obtain the email address of the current user.
So let's work a little bit harder to provide sensible defaults.
=> Improve the default user name & email logic

git-gui/git-gui.sh
On Windows using /git-bash.exe is preferable over using bash because
/git-bash.exe respects the users preferred terminal
=> git-gui: Use /git-bash.exe if available

config.mak.uname
Reference: http://wiki.osdev.org/Stack_Smashing_Protector
This was raised to me privately recently as a suggestion to harden Git from buffer overflows. From the link above:
> The Stack Smashing Protector (SSP) compiler feature helps detect stack buffer overrun by aborting if a secret value on the stack is changed. This serves a dual purpose in making the occurrence of such bugs visible and as exploit mitigation against return-oriented programming.
I've been looking into building the latest version of Git for Windows with this flag enabled, and am running through the test suite with these parameters:
> CFLAGS="-g -O2 -Wall -fstack-protector" make test
This injects a stack smashing protector into "functions with vulnerable objects". There's also some tougher options for GCC that can be used …
=> Build Git with Stack Smashing Protector enabled

contrib/buildsystems/engine.pl
Was getting `Can't use an undefined value as an ARRAY reference at /usr/src/git/contrib/buildsystems/engine.pl line 341.` when running `perl contrib/buildsystems/generate -g Vcproj`
Was falling over on `invalidcontinue.obj` by translating it to `invalidcontinue.cbj`. Even after fixing regex, it turns out `invalidcontinue.c` doesn't exist anyway, so we now first check for existence.
Signed-off-by: Duncan Smart <duncan.smart@gmail.com>
=> Fix Visual Studio .sln/.vcproj generation.

compat/mingw.c
Pull request for issue https://github.com/git-for-windows/git/issues/598
=> Use GetFinalPathNameByHandleW instead of GetLongPathNameW to get full path

.github/ISSUE_TEMPLATE.md
This adds an template to the form when you create a new issue against this repository.
Example: https://github.com/shiftkey/testing-issue-template/issues/new
It's contents mostly reflect the documented [wiki](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) instructions, but helps to put this more into users faces when they land here.
=> added issue template mirroring wiki notes

gitk-git/gitk
When using remotes (with git-flow especially), the remote reference names
are almost always wordwrapped in the "list references" window because it's
somewhat narrow by default. It's possible to resize it with a mouse,
but it's annoying to have to do this every time, especially on Windows 10,
where the window border seems to be only one (1) pixel wide, thus making
the grabbing of the window border tricky.
=> Make the "list references" default window width wider

git-gui/git-gui.sh
This fix refers https://github.com/git-for-windows/git/issues/664
After `git merge --squash` git creates .git/SQUASH_MSG (UTF-8 encoded)
which contains squashed commits. When run `git gui` it copies SQUASH_MSG
to PREPARE_COMMIT_MSG, but without honoring UTF-8. This leads to encoding
problems on `git gui` commit prompt.
The same applies on git cherry-pick conflict, where MERGE_MSG is created
and then is copied to PREPARE_COMMIT_MSG.
In both cases PREPARE_COMMIT_MSG must be configured to store data in UTF-8.
Signed-off-by: yaras <yaras6@gmail.com>
=> [WIP] Fix initial git gui message encoding

credential.c
Fixes: https://github.com/git-for-windows/git/issues/675
When reading username PROMPT_ASKPASS is unnecessary.
Signed-off-by: yaras <yaras6@gmail.com>
---
After my change, username is asked in command prompt (without asterisks) and user password in _Open SSH prompt_ (with asterisks).
What you think about such solution?
=> Fixed masking username with asterisks when reading credentials

CONTRIBUTING.md
Opening this up to start a discussion about updating and adapting the CC template, which feels more succinct than what was previously provided. 
[Rendered Markdown](https://github.com/shiftkey/git/blob/patch-1/CONTRIBUTING.md)
I'll have another read over what was covered in #200 to see what changes might need to be re-applied but let me know how this feels to the contributors, so we can tweak it to suit our situation.
=> Update CONTRIBUTING.md to Contributor Covenant v1.4

git-gui/lib/commit.tcl
git commit --amend preserves the author details unless --reset-author is
given.
git-gui discards the author details on amend.
Fix by reading the author details along with the commit message, and
setting the appropriate environment variables required for preserving
them.
Reported long ago in the mailing list[1].
[1] http://article.gmane.org/gmane.comp.version-control.git/243921
=> git-gui: Do not reset author details on amend

compat/mingw.h, t/t6026-merge-attr.sh, tempfile.c
When testing a merge driver which spawns a merge server (for future merges)
I got the following error:
> Rename from 'xxx/.git/index.lock' to 'xxx/.git/index' failed. Should I try again? (y/n)
Only after I stop the merge server the lock is released.
This is caused by [windows handle inheritance](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724466%28v=vs.85%29.aspx)
Starting childs with bInheritHandles==FALSE does not work.
(For some reason the merge commit window did not pop up.)
However creating the handle with bInheritHandle==FALSE does seem to work.
Although I think this should not break anything, it would be great to get some feedback on this.
mcve:
```shell
git init
cat > mergetest.sh << EOF
#!/bin/sh
echo mergetest.sh
sleep 60 &
EOF
git config --local …
```
=> Make sure temporary file handles are not inherited by child processes

bundle.c, t/tgfw790-git-bundle.sh
issue #790: git bundle create does not close handle to *.lock file
This problem happens when an user tries to create an empty bundle, using the
following command:  `git bundle create <bundle> <revlist>` and when <revlist>
resolve to an empty list (for example, like `master..master`), `git bundle` fails
and warn the user about how it don't want to create empty bundle.
In that case, git tries to delete the `<bundle>.lock` file, and since there's still
an open file handle, fails to do so and ask the user if it should retry (which will
fail again).
The lock can still be deleted manually by the user (and it is required if the user
want to create a bundle after revising his rev-list).
Signed-off-by: Gaël Lhez <gael.lhez@gmail.com>
=> `git bundle create <bundle>` leaks handle the revlist is empty.

builtin/help.c, compat/mingw.c, compat/mingw.h
The Windows flavor of git calls ShellExecute to view web pages.  This call
launches the default handler for .html files.  The user is not able to
configure an alternative despite git having full support for doing so on
Windows.
The original request for this change dates back to 12-May-2014, and [refers
to dropping commit 4804aab][1] from the msysgit repository.  This is exactly
what this commit does.
[1]: https://github.com/msysgit/msysgit/issues/139
=> mingw: delete call to ShellExecute for opening help.

help.c, help.h
@dscho This is my attempt to add build platform information to the output of `git version --build-options` for [Issue #846](https://github.com/git-for-windows/git/issues/846). For now it only understands x86 and x86_64, but I plan to extend the process to include other platforms as well (so that this hopefully won't end up being a Git for Windows specific item).
At present all of the 32-bit variants are collapsed into *x86*, which made sense to me at the time but may or may not be the most desirable approach. For example:
```
$ uname -m
i686
$ git version --build-options
git version 2.9.3.windows.2.826.gd486be9
sizeof-long: 4
machine: x86
```
=> Add reporting of build platform

.github/ISSUE_TEMPLATE.md
MICRO ISSUE TRACKER: portability problems in suggested commands
```
commit 3c8601c3b512ad97d0e420cef5b34b28425dae38
Author: Clive Chan <cc@clive.io>
Date:   Fri Aug 12 13:46:25 2016 -0400
Add detail to ISSUE_TEMPLATE setup questions
With the addition of the architecture (x86/x86_64) to git --version
--build-options, it's good to add that to the Git version question.
On the Windows version question, prompted for "Vista, 7, 8, 10? to
indicate exactly what we're talking about. Also added `cmd /c ver as a
command to run to get the Windows version, but it's not portable yet so
that needs fixing before merging.
On the installation options question, added `cat /etc/install-options.txt`
to provide more information. This also is not portable and also needs to
be fixed.
Relevant Links:
This is part …
```
=> ISSUE_TEMPLATE for #846

.github/ISSUE_TEMPLATE.md
Correct a one-character typo in the issue reporting template, for a
command which bug-reporters are requested to run in order to gather
the installation options.
=> Fix typo in issue reporting template

config.mak.uname
Use OpenSSL SHA1 routines rather than builtin block-sha routines.
This improves performance on SHA1 operations on Intel processors.
=> sha1: use openssl sha1 routines on mingw

git-cvsexportcommit.perl
This fixes a bug encountered when using cvsnt + msys + git. It seems like the output of `cvs status` had \r\n in it, and caused the command to fail. This fixes that.
=> git-cvsexportcommit.perl: Force crlf translation

preload-index.c
Teach preload-index to avoid lstat() calls for index-entries
with skip-worktree bit set.  This is a performance optimization.
During a sparse-checkout, the skip-worktree bit is set on items
that were not populated and therefore are not present in the
worktree.  The per-thread preload-index loop performs a series
of tests on each index-entry as it attempts to compare the
worktree version with the index and mark them up-to-date.
This patch short-cuts that work.
On a Windows 10 system with a very large repo (450MB index)
and various levels of sparseness, performance was improved
in the {preloadindex=true, fscache=false} case by 80% and
in the {preloadindex=true, fscache=true} case by 20% for various
commands.
=> preload-index: avoid lstat for skip-worktree items

builtin/add.c
Teach "add" to use preload-index and fscache features
to improve performance on very large repositories.
During an "add", a call is made to run_diff_files()
which calls check_remove() for each index-entry.  This
calls lstat().  On Windows, the fscache code intercepts
the lstat() calls and builds a private cache using the
FindFirst/FindNext routines, which are much faster.
Somewhat independent of this, is the preload-index code
which distributes some of the start-up costs across
multiple threads.
=> add: use preload-index and fscache for performance

read-cache.c
Clear the precompute flag in create_alias_ce().
It might be possible to use the precompute_ fields from the
alias in the new one, but its not worth the bother.
=> fixup! name-hash: precompute hash values during preload-index

read-cache.c
This is a performance optimization.
Teach do_read_index() to call verify_hdr() using a thread
and allow SHA1 verification to run concurrently with the
parsing of index-entries and extensions.
For large index files, this cuts the startup time in half.
=> read-cache: run verify_hdr() in background thread

Makefile, cache.h, read-cache.c, t/helper/test-strcmp-offset.c, t/t0065-strcmp-offset.sh
Teach add_index_entry_with_check() and has_dir_name()
to see if the path of the new item is greater than the
last path in the index array before attempting to search
for it.
This is a performance optimization.
During checkout, merge_working_tree() populates the new
index in sorted order, so this change saves at least 2
lookups per file.
=> read-cache: speed up add_index_entry during checkout

string-list.c
Use ALLOC_GROW() macro when reallocing a string_list array
rather than simply increasing it by 32.  This is a performance
optimization.
During status on a very large repo and there are many changes,
a significant percentage of the total run time was spent
reallocing the wt_status.changes array.
This change decreased the time in wt_status_collect_changes_worktree()
from 125 seconds to 45 seconds on my very large repository.
=> string-list: use ALLOC_GROW macro when reallocing string_list

compat/poll/poll.c
This replaces PR #993. I was doing that one with the GitHub website but
can't complete it there.
Note that @linquize, @PhilipOakley, and @dscho were having a discussion
about Win XP support and that should conclude before accepting this PR.
From Visual Studio 2015 Code Analysis: Warning C28159 Consider using
'GetTickCount64' instead of 'GetTickCount'.
Reason: GetTickCount overflows roughly every 49 days. Code that does not
take that into account can loop indefinitely. GetTickCount64 operates on
64 bit values and does not have that problem.
Signed-off-by: Steve Hoelzer <shoelzer@gmail.com>
=> poll: Use GetTickCount64 to avoid wraparound issues

builtin/commit.c
If the user has specified '--no-lock-index' when calling git-status, it only seems reasonable that the user intends that option to be carried through to any child forks/procs as well. Currently, the '--no-lock-status' call is lost when submodules are checked. This change places the desired option into the environment, which is in turn passed down to all subsequent children.
With cmd_status checking for '--no-lock--status' first from args then from environment, we're able to keep the option set in all children.
=> Carry non-locking status value in the environment.

diffcore-rename.c
Teach register_rename_src() to see if new file pair
can simply be appended to the rename_src[] array before
performing the binary search to find the proper insertion
point.
This is a performance optimization.  This routine is called
during run_diff_files in status and the caller is iterating
over the sorted index, so we should expect to be able to
append in the normal case.  The existing insert logic is
preserved so we don't have to assume that, but simply take
advantage of it if possible.
=> diffcore-rename: speed up register_rename_src

connect.c, t/t5601-clone.sh
When users want to pass some additional arguments to [tortoise]plink via
GIT_SSH, for example, setting a private key, the user is required to either
use a shell script named plink or tortoiseplink or duplicate the logic
that's already in Git for passing the correct style of command line
arguments, which can be difficult, error prone and annoying to get right.
They could have used GIT_SSH_COMMAND but Git doesn't detect [tortoise]plink
in this environment variable, meaning that Git would pass the wrong style
of command line arguments.  For example -p instead of -P.
This patch uses the logic that was used to recognize [tortoise]plink in
GIT_SSH for the GIT_SSH_COMMAND environment variable, allowing to use
GIT_SSH_COMMAND with [tortoise]plink directly.
Signed-off-by: Segev Finer …
=> connect: recognize [tortoise]plink in GIT_SSH_COMMAND

Documentation/git.txt, compat/mingw.c, t/t0001-init.sh
On Windows, file handles need to be marked inheritable when they need to
be used as standard handles for a newly spawned process. The problem with
that, of course, is that the "inheritable" flag is global and therefore
can wreak havoc with highly multi-threaded applications.
Let's introduce a set of environment variables (GIT_REDIRECT_STDIN and
friends) that point to files, or even better, named pipes and that are
used by the spawned Git process. This helps work around above-mentioned
issue.
=> mingw: add experimental feature to redirect standard handles

git-gui/git-gui.sh
git-gui tries to temporary set GIT_DIR for running commands
and restore it back after it started. But in case of GIT_DIR which was
not set prior to invocation it is not unset after it.
Fix it.
Signed-off-by: Max Kirillov <max@max630.net>
=> git-gui: correctly restore GIT_DIR after invoking commands

compat/win32/fscache.c
Teach FSCACHE to remember "not found" directories.
This is a performance optimization.
FSCACHE is a performance optimization available for Windows.  It
intercepts Posix-style lstat() calls into an in-memory directory
using FindFirst/FindNext.  It improves performance on Windows by
catching the first lstat() call in a directory, using FindFirst/
FindNext to read the list of files (and attribute data) for the
entire directory into the cache, and short-cut subsequent lstat()
calls in the same directory.  This gives a major performance
boost on Windows.
However, it does not remember "not found" directories.  When STATUS
runs and there are missing directories, the lstat() interception
fails to find the parent directory and simply return ENOENT for the
file -- it does not remember that the …
=> fscache: add not-found directory cache to fscache

.github/ISSUE_TEMPLATE.md
The _TODO_ entries in the Issues_template are easily misunderstood
as residual developer actions, rather than a place holder for user
data entry.
Replace the _TODO_ with positively directed actions for the user
("you/your") to perform. Ease off on the tone toward the end.
Signed-off-by: Philip Oakley <philipoakley@iee.org>
=> Issues-Template: remove '_TODO_'s; use kinder words

read-cache.c
Teach do_write_index() to close the index.lock file
before getting the mtime and updating the istate.timestamp
fields.
On Windows, a file's mtime is not updated until the file is
closed.  On Linux, the mtime is set after the last flush.
=> read-cache: close index.lock in do_write_index

Makefile
Teach main Makefile to also delete the PDB files for the
various EXE files during "make MSVC=1 clean".
Previously, we only deleted the PDB files associated with
individual .o files.
=> Makefile: clean EXE PDBs when MSVC=1

Documentation/git-config.txt, compat/mingw.c
Fixed the confusing and inconsistent documentation for this configuration file
by
- aligning it with the already existing upstream predecence rules
- removing the XP-hack using ``$ALLUSERSPROFILE/Application Data` instead
of `$PROGRAMDATA` both in code and in docu.
Signed-off-by: Andreas Heiduk <asheiduk@gmail.com>
=> Align documentation for C:\ProgramData\Git\config

compat/mingw.c, compat/win32/exit-process.h
This PR depends on https://github.com/git-for-windows/msys2-runtime/pull/15.
The idea is that the MSYS2 runtime will no longer kill Git's processes using `TerminateProcess()`, but by injecting a thread calling `ExitProcess()`, which in turn allows Git's `atexit()` handlers to run.
*NOTE*: this does not mean that we all of a sudden have POSIX semantics. Far from it: there is still no real signal handling (think `SIGSTOP` and `SIGCONT`), and the *signal handlers* are not run.
Git's source code amazingly seems to be prepared for that case, as most (or all?) signal handlers simply enter code paths that are *also* entered by atexit handlers.
For example, if a long-running `git clone` is interrupted by Ctrl+C, or by a fatal error, does not matter: in both cases do we want to clean up after us, …
=> Handle Ctrl+C in Git Bash nicely

dir.c, t/t7061-wtstatus-ignore.sh
We meticulously pass the `exclude` flag to the `treat_directory()`
function so that we can indicate that files in it are excluded rather
than untracked when recursing.
But we did not yet treat submodules the same way.
=> status: do not get confused by submodules in excluded directories

compat/mingw.c
This Pull Request is intended to supersede https://github.com/git-for-windows/git/pull/1184.
The main difference is that I fixed a rather serious bug (the return value was declared incorrectly, possibly fooling Git into believing that it could create a symbolic link when it really failed, and that really happened here during my tests), and that the file/directory flags are modified only once. I also use the `GetVersion()` API instead of the POSIX-y `uname()`.
=> Support creating symlinks outside elevated sessions

compat/vcbuild/packages.config, contrib/buildsystems/Generators/Vcxproj.pm
Here is a fix for building inside VS2017 using the generated SLN and VCXPROJ files in vs/master.
For some reason, the existing PERL-generated project files built fine using VS2015, but failed to
link when building with VS2017 (with unsatisfied references in zlib and then openssl).
The fix here, adds explicit .lib references to the AdditionalDependencies parameter.  I left a TODO
in the commit message describing a possibly simpler fix.
@dscho Please see if this looks right to you.  I managed to get everything to compile and link, but
I wasn't sure how you were using some of the project dependencies and error handling at the bottom
of the resulting vcxproj files, so you may want to refactor this.  However you want to handle this is
fine with me.  Thanks!
=> VS2017 vcxproj

compat/mingw.c
It was observed that the current implementation of of get_proc_addr()
fails to load the kernel32.dll with code ERROR_INVALID_PARAMETER.
Probably the reason is that kernel32.dll is already loaded. The
behavior was seen at Windows SP1, both 32bit and 64bit. Probably it
would behave same way in some or all other Windows versions.
This breaks all usages of "clone --local", including the automatic
tests where they call it.
The function CreateHardLink is available in all supported Windows
versions (since Windows XP), so there is no more need to resolve it
in runtime.
=> mingw: use CreateHardLink directly

compat/win32/fscache.c, compat/win32/fscache.h, dir.c, git-compat-util.h
Teach read_directory_recursive() and add_excludes() to
be aware of optional fscache and avoid trying to open()
and fstat() non-existant ".gitignore" files in every
directory in the worktree.
The current code in add_excludes() calls open() and then
fstat() for a ".gitignore" file in each directory present
in the worktree.  Change that when fscache is enabled to
call lstat() first and if present, call open().
This seems backwards because both lstat needs to do more
work than fstat.  But when fscache is enabled, fscache will
already know if the .gitignore file exists and can completely
avoid the IO calls.  This works because of the lstat diversion
to mingw_lstat when fscache is enabled.
This reduced status times on a 350K file enlistment of the
Windows repo on a NVMe SSD by 0.25 seconds. …
=> dir.c: make add_excludes aware of fscache during status

fetch-pack.c
When I do git fetch, git reads entries in .git/objects/pack for every refs in local repository.
By enabling fscache, directory list up in .git/objects/pack for each refs is cached.
Without fscache, such behavior causes long running time when we do git fetch in local repository having many refs.
This patch improves execution time in such case, especially in very large repository like chromium.
In my windows workstation, this patch improves git fetch time from more than 3 minutes to less than 20 seconds for chromium repository.
=> enable fscache while iterating every local refs

fetch-pack.c
This reverts commit 09ccec4.
Using fscache here is not right way.
It is better to specify OBJECT_INFO_QUICK flag for has_object_file instead.
This flag prevents directory list up for each refs also.
=> Revert "enable fscache while iterating every local refs"

compat/win32/fscache.c, compat/win32/fscache.h, dir.c, git-compat-util.h
Fix regression described in:
https://github.com/git-for-windows/git/issues/1392
which was introduced in:
https://github.com/git-for-windows/git/commit/b2353379bba414e6c00dde913497cc9c827366f2
When the user has a .gitignore file that is a symlink, the fscache
optimization introduced above caused the stat-data from the symlink,
rather that of the target file, to be returned.  Later when the ignore
file was read, the buffer length did not match the stat.st_size field
and we called die("cannot use <path> as an exclude file")
Added code to replace the stat-data when the path is a symlink.  This
preserves the effect of the performance gains for the normal case where
it is not a symlink.
=> dir.c: regression fix for add_excludes with fscache

builtin/checkout.c
This is to speed up git checkout for directory in very large repositories.
Taking file stats while directory traversing is faster than
stating to each files on windows.
`git checkout .` in master branch of chromium repositry, having 284659 files,
takes more than 18 seconds.
This patch improved the time to around 4 seconds on my SSD laptop.
=> checkout.c: enable fscache for checkout_entry

builtin/clone.c, t/t5600-clone-fail-cleanup.sh
(Patch series provided by Jeff King <peff@peff.net>)
=> When dest dir is specified and clone breaks for any reason, don't remove the dest dir

fetch-pack.c
When I do git fetch, git call file stats under .git/objects for each
refs. This takes time when there are many refs.
By enabling fscache, git takes file stats by directory traversing and that
improved the speed of fetch-pack for repository having large number of
refs.
In my windows workstation, this improves the time of `git fetch` for
chromium repository like below. I took stats 3 times.
* With this patch
TotalSeconds: 9.9825165
TotalSeconds: 9.1862075
TotalSeconds: 10.1956256
Avg: 9.78811653333333
* Without this patch
TotalSeconds: 15.8406702
TotalSeconds: 15.6248053
TotalSeconds: 15.2085938
Avg: 15.5580231
=> fetch-pack.c: enable fscache for stats under .git/objects

builtin/reset.c
In git reset --hard, unpack-trees() is called with oneway_merge().
oneway_merge calls lstat for each files in a repository.
It is bottleneck of git reset --hard, especially in large repository.
This patch improves time by using fscache.
In chromium repository, time of git reset --hard is changed like below.
I took 3 times stats in the repository.
master:
TotalSeconds: 21.0337971
TotalSeconds: 20.0046612
TotalSeconds: 20.6501752
Avg: 20.5628778333333
this patch:
TotalSeconds: 4.8552376
TotalSeconds: 4.8722343
TotalSeconds: 4.9268245
Avg: 4.88476546666667
=> reset.c: enable fscache

Documentation/config.txt, http.c
Fixes #1446 
Opening this up early to gather feedback (I'm not strong on curl's internals) as I think we're all in agreement on the approach:
=> adding http.schannel.checkRevoke support

compat/terminal.c
This fixes the issue identified in https://github.com/git-for-windows/git/issues/1498 where Git would not fall back to reading credentials from a Win32 Console when the credentials could not be read from the terminal via the Bash hack (that is necessary to support running in a MinTTY).
Tested in a Powershell window.
=> Fix terminal prompt

builtin/checkout.c, compat/win32/fscache.c, compat/win32/fscache.h, entry.c, git-compat-util.h, t/t7201-co.sh
This is retry of #1419.
I added flush_fscache macro to flush cached stats after disk writing
with tests for regression reported in #1438 and #1442.
git checkout checks each file path in sorted order, so cache flushing does not
make performance worse unless we have large number of modified files in
a directory containing many files.
Using chromium repository, I tested `git checkout .` performance when I
delete 10 files in different directories.
With this patch:
TotalSeconds: 4.307272
TotalSeconds: 4.4863595
TotalSeconds: 4.2975562
Avg: 4.36372923333333
Without this patch:
TotalSeconds: 20.9705431
TotalSeconds: 22.4867685
TotalSeconds: 18.8968292
Avg: 20.7847136
I confirmed this patch passed all tests in t/ with core_fscache=1.
=> checkout.c: enable fscache for checkout again

Documentation/git.txt
Git documentation refers to $HOME and $XDG_CONFIG_HOME often, but does not specify how or where these values come from on Windows where neither is set by default. The new documentation reflects the behavior of setup_windows_environment() in compat/mingw.c.
=> Document how $HOME is set on Windows

CONTRIBUTING.md
Whitespace errors are easy to create but hard to check manually. Add
two git commands that detect these whitespace errors to the commit
cleanup section of CONTRIBUTING.md.
=> CONTRIBUTING.md: check for whitespace before submitting

Documentation/git.txt
Fixing the header for Environment Variables > System header added in b2956b369ab926417652def4cd7f85e9f475cd53.
Original PR: https://github.com/git-for-windows/git/pull/1548
=> Fix doc formatting error in git.txt

compat/mingw.c
Fixes https://github.com/git-for-windows/git/issues/1220
=> mingw: quote argument to 'sh' if it contains brace

compat/mingw.c
Fixes #1646 as described in the issue.
=> fixup! Win32: symlink: add support for symlinks to directories

contrib/buildsystems/Generators/Vcxproj.pm
Add new condition to invoke vcpkg_install.bat: it's not enough to check
the presence of folder vcpkg. We need to check the presence of some
header files because this is one of the main goals of this script.
Previous build attempt could be aborted, so the folder will exist but
the project will not be built properly.
Signed-off-by: Olga Telezhnaia <olyatelezhnaya@gmail.com>
=> vcxproj: change build logic

CONTRIBUTING.md
A few new dependencies are required for building Git on Linux and running the performance tests.
=> Update CONTRIBUTING.md instructions

Documentation/config.txt, http.c
The `http.*` config settings can be limited to specific URLs via
`http.<url>.*`. Unfortunately, this prevented our beautiful
`http.schannel.checkRevoke` *from ever working*, as the `schannel` part
was interpreted as a URL.
Let's just change this completely, by avoiding having "a middle part"
that is then interpreted as a URL.
As a fringe benefit, this now also allows users to disable the
revocation checking on a URL-by-URL basis.
This fixes https://github.com/git-for-windows/git/issues/1531 (for real)
=> http: rename http.schannel.checkRevoke to http.schannelCheckRevoke

README.md
Add another build badge, in addition to the CR/LF one: this one is for
the Windows/macOS/Linux builds.
=> fixup! README.md: Add a Windows-specific preamble

Documentation/config.txt
I overlooked this while reviewing #1747 - not sure if it should be fully qualified to `http. schannelUseSSLCAInfo` but I'll let the reviewer weigh in.
=> updated mention of http.useSSLCAInfo to use correct name

git-gui/git-gui.sh
Git started to support a couple of features in the meantime, one of which is to override the hooks path via the config.
Let's teach Git GUI about them.
This fixes #1755 
/cc @luismbo
=> git-gui: respect modern hooks paths

compat/vcbuild/find_vs_env.bat
Completely convert the pathname expoted in the %msvc_bin_dir_msys%
variable to MSYS format with forward slashes rather than a mixture
of forward and back slashes.
This solves an obscure problem observed by some developers:
[...]
http-push.c
CC remote-curl.o
remote-curl.c
* new script parameters
GEN git-instaweb
sed: -e expression #7, char 155: invalid reference \2 on `s' command's RHS
make: *** [Makefile:2023: git-instaweb] Error 1
=> find_vs_env.bat: Fix bin dir path used by msys

config.c, t/t0020-crlf.sh
A regression introduced in 8462ff43 ("convert_to_git(): safe_crlf/checksafe becomes int conv_flags", 2018-01-13) back in Git 2.17 cycle caused autocrlf rewrites to produce a warning message despite setting safecrlf=false.
This should fix https://github.com/git-for-windows/git/issues/1242
/cc @tboegi
=> config.c: fix regression for core.safecrlf false

builtin/gc.c, t/t5510-fetch.sh
Teach gc --auto to release pack files before auto packing the repository
to prevent failures when removing them.
Also teach the test 'fetching with auto-gc does not lock up' to complain
when it is no longer triggering an auto packing of the repository.
Fixes https://github.com/git-for-windows/git/issues/500
=> gc --auto: release pack files before auto packing

compat/mingw.c
Fix compiler error introduced in this commit:
error C2061: syntax error: identifier 'handle_ctrl_c'
Implements the fix suggested by @kgybels in #1735
=> fixup! mingw: really handle SIGINT

builtin/config.c
As reported here[0], Microsoft Visual Studio 2017.2 and "gcc -pedantic"
don't understand the forward declaration of an unsized static array.
They insist on an array size:
d:\git\src\builtin\config.c(70,46): error C2133: 'builtin_config_options': unknown size
The thread [1] explains that this is due to the single-pass nature of
old compilers.
To work around this error, introduce the forward-declared function
usage_builtin_config() instead that uses the array
builtin_config_options only after it has been defined.
Also use this function in all other places where usage_with_options() is
called with the same arguments.
[0]: https://github.com/git-for-windows/git/issues/1735
[1]: https://groups.google.com/forum/#!topic/comp.lang.c.moderated/bmiF2xMz51U
Fixes …
=> builtin/config: work around an unsized array forward declaration

connect.h, convert.c, path.h, refs/refs-internal.h, sequencer.c, string-list.c, utf8.c
Merge bb/pedantic to fix MSVC compile warnings
=> Merge bb/pedantic 

read-cache.c
On file systems that support it, this can dramatically speed up operations
like add, commit, describe, rebase, reset, rm that would otherwise have to
lstat() every file to "re-match" the stat information in the index to that
of the file system.
On a synthetic repo with 1M files, "git reset" dropped from 52.02 seconds to
14.42 seconds for a savings of 72%.
Signed-off-by: Ben Peart <Ben.Peart@microsoft.com>
=> Enable the filesystem cache (fscache) in refresh_index().

builtin/pack-objects.c, pack-objects.c, pack-objects.h, t/t5319-pack-large-objects.sh
It was reported in https://github.com/git-for-windows/git/issues/1839 that `git gc` crashes under certain circumstances. The MCVE provided by @thomas-patzig and the initial analysis by @kgybels were invaluable to come up with this PR. Thank you!
=> Fix occasional segmentation fault in `git gc`

compat/poll/poll.c
I noticed that a recent GitGitGadget build failed in the Windows phase, with `compat/poll/poll.h` problems all over the place.
Turns out that this is caused by the recent upgrade of the mingw-w64 headers and crt files (7.0.0.5233.e0c09544 -> 7.0.0.5245.edf66197, which I assume now enforces Vista as minimal Windows version also for all mingw-w64 projects).
Luckily, in Git for Windows' `master`, we already had changes to require Vista (for unrelated reasons: to restrict the std handle inheritance when spawning new processes). But we missed one thing: we still included the `winsock2.h` header file in `compat/poll/poll.c` *after* including `poll.h`, so we did not really override the constants and structs defined in the former. Let's fix this.
=> Fix up compat/poll/poll.c

builtin/rebase.c, git-gui/git-gui.sh
One thing is a fix for a patch in the `builtin-rebase` part: it [had been pointed out](https://public-inbox.org/git/d5d0f6c3-748b-b83f-f9d4-2812f4509313@ramsayjones.plus.com/) that one of the patches introduced a `0` where a `NULL` would have been correct (I had missed this because it was not sent as a reply to the original mail thread).
The other thing is more subtle, and even more worrisome: due to the way we start with a merging rebase, all patches that had been part of a previous branch thicket are assumed to be applied already. But this is not the case for branches we merged directly from https://github.com/gitster/git's branches: they would have to be re-applied. Previously, this was not a problem because merging rebases always rebased *everything* on top of the initial merge …
=> Two things I totally forgot

compat/mingw.c
The usage of the uninitialized variable `findbuf` on https://github.com/git-for-windows/git/blob/master/compat/mingw.c#L858 causes undefined behavior in libgit (if `if (fdata.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT) {` is false).
This is fixed by initializing it properly which is only present in Git for Windows but not vanilla Git.
=> Don't use uninitialized variable

t/helper/test-cmp.c, t/t0001-init.sh
It's an obscure case, granted, but @jamill encountered it.
=> Fix t0001 when the current working directory differs in case from the canonical form

compat/win32/fscache.c
Use FindFirstFileExW with FindExInfoBasic to avoid forcing NTFS to look up
the short name.  Also switch to a larger (64K vs 4K) buffer using
FIND_FIRST_EX_LARGE_FETCH to minimize round trips to the kernel.
In a repo with ~200K files, this drops warm cache status times from 3.19
seconds to 2.67 seconds for a 16% savings.
=> fscache: use FindFirstFileExW to avoid retrieving the short name

builtin/commit.c
At the end of the status command, disable and free the fscache so that we don't leak the memory and so that we can dump the fscache statistics.
=> status: disable and free fscache at the end of the status command

compat/mingw.c, compat/mingw.h
=> Add a helper function to start GDB that was already attached to the current process

compat/mingw.c, compat/mingw.h
- Replaced `ipv6_*` callers by non-prefixed versions.
- Removed `ipv6_*` pointer functions and stub functions.
- Reverted `ensure_socket_initialization`.
=> [Outreachy] Removed ipv6 fallback

builtin/add.c
At the end of the add command, disable and free the fscache so that we don't leak the memory and so that we can dump the fscache statistics.
=> At the end of the add command, disable and free the fscache

compat/win32/fscache.c
Track fscache hits and misses for lstat and opendir requests.  Reporting of statistics is done when the cache is disabled for the last time and freed and is only reported if GIT_TRACE_FSCACHE is set.
Sample output is:
11:33:11.836428 compat/win32/fscache.c:433 fscache: lstat 3775, opendir 263, total requests/misses 4052/269
=> fscache: add fscache hit statistics

builtin/add.c, builtin/checkout.c, builtin/commit.c, compat/win32/fscache.c, compat/win32/fscache.h, fetch-pack.c, git-compat-util.h, mem-pool.c, preload-index.c, read-cache.c
This patch series encompasses a set of changes to the fscache that underlies git's lstat() and opendir(). In addition to some additional tracing, the fscache is enhanced to reduce thread contention and take advantage of the new mem_pool heap manager.  The net result is ~25% reduction to preload_index() vs the old fscache.
=> Improve performance of fscache

compat/mingw.c, compat/win32/fscache.c, compat/win32/fscache.h
The recent change to make fscache thread specific relied on fscache_enable() called first from the primary thread before being called in parallel worker threads.  Make that more robust and protect it with a critical
section to avoid any issues.
Helped-by: Johannes Schindelin <johannes.schindelin@gmx.de>
=> fscache: make fscache_enable() thread safe

compat/win32/fscache.c, compat/win32/ntifs.h
Using FindFirstFileExW() requires the OS to allocate a 64K buffer for each directory and then free it when we call FindClose().  Update fscache to call the underlying kernel API NtQueryDirectoryFile so that we can do the buffer management ourselves.  That allows us to allocate a single buffer for the lifetime of the cache and reuse it for each directory.
This change improves performance of 'git status' by 18% in a repo with ~200K and 30k folders.
Documentation for NtQueryDirectoryFile can be found at:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntquerydirectoryfile
https://docs.microsoft.com/en-us/windows/desktop/FileIO/file-attribute-constants
https://docs.microsoft.com/en-us/windows/desktop/fileio/reparse-point-tags
To determine if the specified …
=>  fscache: teach fscache to use NtQueryDirectoryFile

config.mak.uname, contrib/buildsystems/Generators/Vcxproj.pm
Unfortunately, the recent restructuring of the environment handling had an unexpected fallout: the `wmain()` function was not actually used in the MSVC build, but the `main()` function was picked up instead, and therefore not only was the environment not handled as we wanted, but the `_wpgmptr` variable was initialized to `NULL` and not pointing to the absolute path of the current executable, causing a segmentation fault (reported by @benpeart).
This PR fixes that.
=> Fix MSVC/Visual Studio build

azure-pipelines.yml
The Windows phase still takes a ton of time, but we can cut corners e.g. by skipping the tests for the `--preserve-merges` mode of `git rebase` (which is soon to be deprecated in favor of `--rebase-merges`, if everything goes according to my plan).
=> Prepare for skipping `git rebase -p` tests on Azure Pipelines

compat/mingw.c, compat/poll/poll.c, compat/win32/exit-process.h, compat/winansi.c
While technically not necessary, it is nice to have code that compiles both with and without the `UNICODE` constant defined.
Practically, this means that we have to use the `*A()` and `*W()` variants of the Win32 API functions explicitly.
=> mingw: safeguard against compiling with `-DUNICODE`

Documentation/config.txt, http.c
This is a backport of https://github.com/git/git/commit/d73019feb44b (which made it already to `next`). It allows setting `http.version` to `HTTP/1.1` or `HTTP/2` to choose the version of the HTTP protocol to use.
This might be important e.g. to let users choose to downgrade to HTTP/1.1 when the desired authentication scheme is incompatible with HTTP/2 (such is the case for NTLM, but we already have a cURL-side patch for that in the pipeline: https://github.com/curl/curl/pull/3345).
=> http: add support selecting http version

.gitattributes, t/.gitattributes, t/t9902-completion.sh
I noticed that our CI builds (see [1] for an example) were returning success much faster than they did before Git v2.20.0. Turns out that there was a test _script_ failure involving the new test hash logic.
```
error: bug in the test script: bad hash algorithm
make[1]: *** [Makefile:56: t0000-basic.sh] Error 1
make[1]: *** Waiting for unfinished jobs....
```
The reason this passed was because we were running this command in our build:
```
make GIT_TEST_OPTS=--quiet -j 10 -C t ||
make GIT_TEST_OPTS=\"-i -v -x\" -k -C t failed 
```
The first `make` failed, but the test script did not record any failed tests and hence the second command succeeded.
The test bug relates to this function added by 2c02b110d "t: add test functions to translate hash-related values":
```
+# Load key-value pairs …
```
=> .gitattributes: ensure t/oid-info/* has eol=lf

builtin/rebase.c
In the VFSforGit project, it was detected that the patches to call the `--am` backend directly (i.e the `builtin-rebase--am` topic branch) introduced a performance regression.
The root cause was that we translated the `move_to_original_branch` to C by using the `reset_head()` function which *always* updated the worktree.
But in the case of `move_to_original_branch`, we want to update the original branch to point at the current revision, and *not* change the worktree at all.
To work around that performance issue, let's teach `reset_head()` to update *only* the refs.
=> Fix a performance regression in the built-in rebase

builtin/rebase.c, t/t5403-post-checkout-hook.sh
This PR fixes a regression introduced by switching to the built-in rebase: the `post-checkout` hook was run in the scripted version but not in the built-in version.
=> Rebase: Run post-checkout hook on checkout

builtin/stash.c, t/t3903-stash.sh
If reset_tree returns a non-zero value, stash_working_tree calls
object_array_clear with &rev.pending before rev is initialized.  This
causes a segmentation fault.  Prevent this by initializing rev before
calling reset_tree.
This fixes #2006.
Signed-off-by: Matthew Kraai <mkraai@its.jnj.com>
=> Initialize rev before using &rev.pending

diff.c
According to getenv(3)'s notes:
The implementation of getenv() is not required to be reentrant.  The
string pointed to by the return value of getenv() may be statically
allocated, and can be modified by a subsequent call to getenv(),
putenv(3), setenv(3), or unsetenv(3).
Since strings returned by getenv() are allowed to change on subsequent
calls to getenv(), make sure to duplicate when caching external_diff_cmd
from environment.
This problem becomes apparent on Git for Windows since fe21c6b285df
(mingw: reencode environment variables on the fly (UTF-16 <-> UTF-8)),
when the getenv() implementation provided in compat/mingw.c was changed
to keep a certain amount of alloc'ed strings and freeing them on
subsequent calls.
This fixes https://github.com/git-for-windows/git/issues/2007:
$ yes n …
=> diff: ensure correct lifetime of external_diff_cmd

Makefile, azure-pipelines.yml, ci/lib.sh, ci/make-test-artifacts.sh, ci/mount-fileshare.sh, ci/run-test-slice.sh, compat/mingw.c, t/helper/test-path-utils.c, t/helper/test-tool.c, t/helper/test-tool.h, t/helper/test-xml-encode.c, t/t0021-conversion.sh, t/t1050-large.sh, t/t5315-pack-objects-compression.sh, t/t9303-fast-import-compression.sh, t/test-lib.sh
Let's backport a few changes from the review on the Git mailing list, really drop the `test_atexit` commits, drop the apt lock hack, parallelize the test suite on Windows, etc
Eventually all of this PR should be squashed into the next iteration of https://github.com/gitgitgadget/git/pull/31
=> Improve Azure Pipelines support

compat/win32/fscache.c
It was reported in https://github.com/git-for-windows/git/issues/1989 and https://github.com/git-for-windows/git/issues/2022 that our new FSCache code (which is quite a bit faster than the old version, partially due to using a low-level API instead of a high-level API) caused regressions on network drives in combination with older Windows versions than Windows 10.
This PR fixes it by adjusting the buffer size to accommodate the limits on older Windows versions (and remember, if the server has an older version, this bug hits, too).
=> Fix a network drive related bug in the new, fast FSCache

archive-tar.c
git-archive uses `gzip -cn` to compress tar files but for this to work, gzip needs to be present on the host system, which sometimes is not the case.
In our implementation, we are trying to add minimal code that will mimic gzip compression, so as to get rid of this gzip dependency
Closes: #1970
=> [FIX] git-archive error, gzip -cn : command not found

.gitattributes
This reverts a patch in Git for Windows' thicket which made it upstream in a slightly different form, and therefore became obsolete.
=> Drop a redundant patch

builtin/repack.c
This patch made it upstream, but due to its nature (empty lines on both sides), it was not dropped during the merging-rebases, but instead duplicated. Let's drop it.
=> Drop duplicate patch

compat/poll/poll.c
Remove another patch that was needed for Windows XP.
=> fixup! poll: lazy-load GetTickCount64()

Documentation/gitattributes.txt, apply.c, builtin/difftool.c, builtin/init-db.c, compat/mingw.c, compat/mingw.h, entry.c, git-compat-util.h, merge-recursive.c, refs/files-backend.c
In git.git's `master`, the `git_check_attr()` function already reflects the fact that it relies on the presence of a Git index: the `git_check_attr()` function takes an explicit `index` parameter, in preparation for some future in which multiple submodules can be processed in the same process (i.e. with multiple Git indexes).
To reflect that in our `.gitattributes` support for symbolic link types, let's redo a part of those patches: instead of hacking into `symlink()`, we implement and use an index-aware function that creates symbolic links.
=> Touch up symlink .gitattributes support

Documentation/gitattributes.txt
`UTF-16-LE-BOM` to `UTF-16LE-BOM`.
this closes https://github.com/git-for-windows/git/issues/2095
=> gitattributes.txt: fix typo

builtin/rebase.c, t/t3400-rebase.sh
It was reported (a bit belatedly) that there was a regression in v2.21.0 where the built-in rebase would update `ORIG_HEAD` one times too many, so that it would not point at the pre-rebase state immediately after a rebase completed.
This regression is related (but not identical) to one that was already reported in early January (which was fixed immediately), and for which a regression test had been promised, but which did not materialize until after v2.21.0. Which is too bad, because that re-regression was totally avoidable.
This patch series fixes that problem, and adds a regression test (better late than never, right?) to avoid re-introducing that regression a third time.
This made it (in a slightly different form, see range-diff below) into git.git's `next` already, via …
=> built-in rebase: pick up the ORIG_HEAD fix early

Makefile
There is a `find` call in the `Makefile` to list all the header files that is pretty expensive on Windows, *especially* in scenarios where there are multiple worktrees as subdirectories of the main worktree, or when there are unrelated worktrees under the main worktree.
This patch already made it into git.git's `next`, and I'd like to have it in Git for Windows early, to accelerate my own development (and that of others, too).
=> Accelerate startup time of `make`

builtin/fetch.c, fetch-pack.c, pkt-line.c
This pair of patches fixes the problem where our CI tests would fail randomly in t5570.9 or t5570.10, and a re-run would "fix" it.
It was integrated into git.git's `next` already, via https://github.com/git/git/commit/59fe6aa5ac38, and will most likely make it into `master` soon.
Let's take this early, to lessen the burden on the person who has to re-run all those CI runs when t5570 fails again (which would be me).
=> Fix t5570 flakiness on macOS

config.mak.uname
Recently the Git for Windows project started the upgrade process to
a MSYS2 runtime version based on Cygwin v3.x.
This has the very notable consequence that `$(uname -r)` no longer
reports a version starting with "2", but a version with "3".
That breaks our build, as df5218b4c30b (config.mak.uname: support MSys2,
2016-01-13) simply did not expect the version reported by `uname -r` to
depend on the underlying Cygwin version: it expected the reported
version to match the "2" in "MSYS2".
So let's invert that test case to test for *anything else* than a
version starting with "1" (for MSys). That should safeguard us for the
future, even if Cygwin ends up releasing versionsl like 314.272.65536.
=> mingw: allow building with an MSYS2 runtime v3.x

compat/poll/poll.c, compat/win32/exit-process.h, kwset.c
Just a couple of things on top of what upstream already fixed for GCC 8.x.
=> Make Git for Windows compile with GCC 8.x

Makefile, azure-pipelines.yml, builtin/push.c, ci/lib.sh, compat/mingw.c, compat/vcbuild/scripts/clink.pl, compat/vcbuild/vcpkg_install.bat, compat/win32/fscache.c, compat/win32/ntifs.h, compat/win32/path-utils.h, compat/winansi.c, config.mak.uname, git-compat-util.h, read-cache.c, sha1-lookup.c
This ensures that our MSVC build becomes a first-class citizen.
=> Let the MSVC build also be tested in the Azure Pipeline

gitk-git/gitk
When `gitk` is faced with *a lot* of refs, it simply passes them to `git rev-list` and `git log` via the command-line without caring about any command-line size limits. On Windows, this fails as soon as the command-line is longer than roughly 32k characters (which is *a lot*, but not if you have over a thousand tags/branches that would amount to a longer command-line than 32k characters, which apparently some users do have).
Based on the excellent groundwork performed in https://github.com/git-for-windows/git/pull/2053, this PR addresses that problem by specifying the revs/files via `stdin`. In contrast to #2053, we try to avoid the full bidirectional inter-process communication: we know in advance what needs to be passed in via `stdin` (it does not depend on any interactive output of the …
=> Fix gitk (long cmdline)

t/t6500-gc.sh
It was always a tricky thing to run Git's scripts with MSYS2 while insisting on running the rest via the non-MSYS2 `git.exe`.
With v3.x of the MSYS2 runtime, this became even trickier, as it now seems that the Cygwin/MSYS2 process IDs no longer are actual Windows process IDs anymore. Or at least `git.exe` cannot open those processes (and `wmic process list` seems not to list them, either).
This PR fixes the (as far as I can tell) only test case that relied on this previously.
=> Prepare the gc tests for v3.x of the MSYS2 runtime

Documentation/config.txt, Documentation/config/sendpack.txt, credential.c, send-pack.c
I recently upstreamed a few more patches to the Git mailing list, and the consensus for these two (https://github.com/gitgitgadget/git/pull/137 and https://github.com/gitgitgadget/git/pull/138) was to drop them, as they are no longer necessary.
=> Drop some obsolete patches

dir.c
This one made it already into core Git's `master`, but we cannot merge it as-is because it is ahead of Git for Windows' current `master` by more than just one commit. So let's cherry-pick it.
=> Backport "untracked cache: fix off-by-one"

sequencer.c, sha1-name.c, t/t3429-rebase-edit-todo.sh
In the [`ever-green.sh` script](https://github.com/git-for-windows/build-extra/blob/master/ever-green.sh), we make use of an obscure, yet powerful feature of the interactive rebase: we use an `exec` command to augment the todo list (to allow for a 2-phase rebase to be executed in a single one, so that the second phase will be executed even if a merge conflict had to be resolved in the first phase).
However, this poses a challenge with the new loose object cache, as we might reference newly-created commits in that new todo list part, and the loose object cache might pretend that those commits do not exist.
Let's fix that.
=> rebase -i: fix re-reading the todo list when newly created objects are referenced

Documentation/config/add.txt, Makefile, add-interactive.c, add-interactive.h, add-patch.c, apply.c, builtin/add.c, builtin/commit.c, builtin/stash.c, ci/run-build-and-tests.sh, commit.h, compat/terminal.c, compat/terminal.h, diff.c, diff.h, git-add--interactive.perl, git-legacy-stash.sh, prefix-map.c, prefix-map.h, repository.c, repository.h, t/README, t/helper/test-prefix-map.c, t/helper/test-tool.c, t/helper/test-tool.h, t/t0016-prefix-map.sh, t/t3701-add-interactive.sh, t/t3904-stash-patch.sh
This reduces not only our dependency on Perl even further, but it also reduces the startup time of `git add -p` substantially.
Note: this PR is currently meant primarily as a way to test this feature thoroughly, with plans to merge it when the patches have been reviewed on the Git mailing list for a bit.
=> Offer a built-in version of `git add -i` and `git add -p`

Documentation/technical/api-parse-options.txt, builtin/difftool.c, git.c, parse-options.c, parse-options.h, t/helper/test-parse-options.c, t/t7800-difftool.sh
This addresses https://github.com/git-for-windows/git/issues/2123
(Well, maybe I should try to get `git difftool --no-index --dir-diff -- ../1 ../2` to work, but it seems like that project would be quite a bit more involved than I can afford right now...)
=> Allow `git difftool --no-index` to run outside of a worktree

add-patch.c, builtin/bisect--helper.c, builtin/rebase--interactive.c, builtin/rebase.c, ci/lib.sh, compat/win32/fscache.c, entry.c, sequencer.c
I only swept the report broadly, looking for some obvious things we might want to fix.
=> Fix some issues reported by Coverity

cache.h, fsmonitor.c, read-cache.c, t/helper/test-read-cache.c, t/t7519-status-fsmonitor.sh
This PR is in response to https://public-inbox.org/git/nycvar.QRO.7.76.6.1903142058130.41@tvgsbejvaqbjf.bet/T/#mb8718fe52e4721dacd3b143a09187ff9090ef4e3
=> Do query the fsmonitor again after the index has been discarded

wt-status.c
Those label commands are currently displayed with their argument resolved as abbreviated commit hash. Not really what we want. We really want the label names instead.
Companion PR to https://github.com/gitgitgadget/git/pull/188.
=> Fix `git status`' display of `git rebase -ir`'s `label` commands

add-interactive.c, prefix-map.c
Before integrating the built-in `add -p` into Git for Windows' `master`, I had actually forgotten about @jeffhostetler's very helpful suggestions. Better late than never ;-)
=> A couple of fixups for add-i-in-c-status-and-help

builtin/am.c, builtin/clone.c, builtin/fetch.c, builtin/gc.c, builtin/merge.c, builtin/rebase.c, builtin/receive-pack.c, builtin/repack.c, commit-graph.c, commit-graph.h, object.c, packfile.c, packfile.h, upload-pack.c
This PR is a backport of https://github.com/gitgitgadget/git/pull/208, which avoids a lock contention in `git gc --auto` where the `git gc` process holds a read lock to the `commit-graph` file (if `core.commitgraph=true`) and the spawned `git commit-graph write` (if `gc.writecommitgraph=true`) tries to overwrite it.
cc @derrickstolee
=> Avoid commit-graph lock contention

apply.c, builtin/update-index.c, cache.h, diff-lib.c, entry.c, fsmonitor.h, preload-index.c, read-cache.c
The `t7519-status-fsmonitor.sh` tests became a *lot* more flaky with the recent fsmonitor fix (`js/fsmonitor-refresh-after-discarding-index`). That fix, however, did not introduce the flakiness, but it just made it much more likely to be hit. And it seemed to be hit *only* on Windows.
The reason, though, is that the fsmonitor feature failed to mark the in-memory index as changed, i.e. in need of writing, and it was the `has_racy_timestamp()` test that hid this bug in most cases (although a lot less on Windows, where the files' mtimes are actually a lot more accurate than on Linux).
This fixes https://github.com/gitgitgadget/git/issues/197
=> Fix racy fsmonitor

Documentation/config/core.txt, compat/mingw.c
It seems that our feature to restrict file handle inheritance to let spawned processes inherit only the standard handles is a bit broken on Vista.
This closes https://github.com/git-for-windows/git/issues/1742
=> Disable the file handle restriction code for Windows Vista and 2008

unpack-trees.c
When updating the skip-worktree bits in the index to align with new
values in a sparse-checkout file, Git scans the entire working
directory with lstat() calls. In a sparse-checkout, many of these
lstat() calls are for paths that do not exist.
Enable the fscache feature during this scan.
In a local test of a repo with ~2.2 million paths, updating the index
with `git read-tree -m -u HEAD` with a sparse-checkout file containing
only `/.gitattributes` improved from 2-3 minutes to 15-20 seconds.
More work could be done to stop running lstat() calls when recursing
into directories that are known to not exist.
=> unpack-trees: enable fscache for sparse-checkout

config.c
This fix already made it into git.git's `master`, via https://github.com/gitgitgadget/git/pull/265.
=> Support compiling with GCC v9.x

builtin/clean.c, cache.h, compat/mingw.c, compat/mingw.h, compat/win32/fscache.c, compat/win32/fscache.h, git-compat-util.h, path.c, t/t7300-clean.sh
This addresses #607.
Based on #1976.
=> Avoid traversing NTFS junction points in `git clean -dfx`

SECURITY.md
GitHub recommends to add a `SECURITY.md` document as a standardized way to let users know about these policies.
=> SECURITY.md: document Git for Windows' policies

config.mak.uname
no longer relevant after moving to PCRE2
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>
=> config.mak.uname: PCRE1 cleanup

sequencer.c, t/t3430-rebase-merges.sh
Resolves #2307 by replacing all non-alphanumeric ascii characters with '-' and appending an _ to prevent clashes with reserved windows filenames.
=> rebase-merges: improve --rebase-merges label generation

gitk-git/gitk
Fixes https://github.com/git-for-windows/git/issues/2293
=> gitk: Escape file paths before piping to git log

SECURITY.md
This should be a one commit adjustment to SECURITY.md to respond to comment git-for-windows#2303 ([comment](https://github.com/git-for-windows/git/pull/2303#issuecomment-524351036))
Provide details of the release candidate versions and snapshots ('nightlies', though they aren't).
Signed-off-by: Philip Oakley <philipoakley@iee.email>
---
hope the 'rc<n>' comes through the .md filtering ok.
=> Security.md: include release candidate and snapshot information

compat/mingw.c
Recently, we hardened the ProgramData support by ignoring the config file when it is owned by a "dubious" user, i.e. by an account other than the local administrators group, the system account or the current user.
Turns out, there is at least one scenario where that config file can be legitimately owned by a specific administrator rather than the administrators group, and that still should not be treated as "dubious". Let's implement code to handle this situation gracefully.
This fixes https://github.com/git-for-windows/git/issues/2304.
=> Do not complain if `C:\ProgramData\Git\config` is owned by a specific administrator

compat/vcbuild/vcpkg_install.bat
While testing out the vs/master branch that should provide a ready-to-go git.sln for compilation with
Visual Studio, I hit a couple of snags.
These ultimately were problems with my local installation, but the sln compilation should offer extra guidance if users fall into the same trap.
The compilation stage that uses the vcpkg download can also fail on slow networks, so a batch file remark is included to inform users who follow-up the error message.
The fixes #2349 (in conjunction with https://github.com/git-for-windows/build-extra/pull/258).
Signed-off-by: Philip Oakley <philipoakley@iee.email>
=> Vcpkg Install: detect lack of working Git, and note possible vcpkg time outs

ci/install-dependencies.sh
I just pushed a fix that was also contributed to git.git via gitgitgadget/git#400, but it _still_ does not fix the problem.
Turns out that @szeder was spot on when he said that we were reluctant to switch to `brew cask install perforce` because stale caches could cause a problem: the `perforce` recipe downloads the latest binaries from Perforce's website, and when that changes, the recipe needs to be updated with the new version number and the new SHA-256. Perforce updated that file on Fri, 11 Oct 2019 20:53:43 GMT most recently, and I offered [a PR to update the recipe](https://github.com/Homebrew/homebrew-cask/pull/70981), and even though that PR was merged, the Azure Pipeline still failed because it still had the old version.
Let's work around this by falling back to pulling …
=> Work around that pesky Homebrew `perforce` problem

add-patch.c, t/t3701-add-interactive.sh
This bug was reported over at https://github.com/git-for-windows/git/issues/2364: the code mishandled comment lines in the diffs (i.e. lines starting with a backslash).
While in that part of the code already, I also added some defensive code, and some comments.
=> Fix a bug in the hunk-splitting code of the built-in `git add -p`

compat/mingw.c
Inspired by https://github.com/gitgitgadget/git/pull/414, this is a minimal fix for the issue that `needs_hiding()` runs right outside the buffer when being passed a path with a trailing slash.
The patch in https://github.com/gitgitgadget/git/pull/414 does too many things: it not only fixes the bug, but rewrites a large part of the function. This late in the -rc phase leading up to v2.24.0, I am not willing to risk such a rewrite.
Cc: @SyntevoAlex
=> Avoid a buffer overrun in `needs_hiding()`

config.c
This makes the output of `git config --show-origin` prettier.
=> config: normalize the path of the system gitconfig

Documentation/config.txt, Documentation/config/sendpack.txt, send-pack.c
Hi @dscho 
this reintroduces the original changeset from Thomas Braun. Hope that everything is well-formed and as expected.
I also opened a separate ticket #2376 for the underlying issue (as outlined a bit in issue #907). For now reintroducing the option should "unbreak" `git push` for the old `git://`-protocol users on Windows.
This also addresses issues #2278 and #2314. The `sendpack.sideband` setting was previously used to work around the stalled `git push` issue on Windows, 2.22 broke this, as the patch was deemed obsolete.
I verified this for now by simply using `git push` versus `git -c sendpack.sideband=false push` against a local server. Provided I can address the underlying issue, the configuration option can probably be removed again. However, otherwise you should pester me …
=> Config option to disable side-band-64k for transport

usage.c
This is based, in part, on https://github.com/gitgitgadget/git/pull/407, but it avoids the complexity incurred by the desire to allow for unlimited messages.
=> Fix t5516 flakiness in MSVC builds

Documentation/git-update-index.txt, builtin/stash.c, builtin/update-index.c, git-legacy-stash.sh, t/t3903-stash.sh, t/t7012-skip-worktree-writing.sh
This Git for Windows PR corresponds to https://github.com/gitgitgadget/git/pull/355, which will most likely _not_ make it into Git v2.24.0.
My colleague Dan Thompson reported a bug in a sparse checkout, where `git stash` (after resolving merge conflicts and then making up their mind to stash the changes instead of committing them) would "lose" files (and files that were not even in the sparse checkout's cone!).
I first considered changing the behavior of `git diff-index` to simply ignore skip-worktree entries. But after re-reading the documentation of the skip-worktree bit, I became convinced that this would be incorrect a fix because the command really does what it advertises to do.
Then, I briefly considered introducing a flag that would change the behavior thusly, but ended up deciding …
=> Fix `git stash` with skip-worktree entries

commit-graph.c, commit-reach.c, object.h, t/t5510-fetch.sh
This is a direct relative of https://github.com/gitgitgadget/git/pull/415, with the intention of merging it in time for Git for Windows v2.24.0.
=> Fix `fetch.writeCommitGraph` failure first fetch

gitk-git/gitk
https://github.com/git-for-windows/git/pull/2297 tried to escape the paths when refreshing, but it was missing a continuation. This led to the error message
```
Error executing git log: wrong # args: should be "escape_filter_paths paths"
```
This fixes https://github.com/git-for-windows/git/issues/2390
=> Fix refresh error in gitk

add-interactive.c, add-patch.c, builtin/add.c, strbuf.c, strbuf.h
=> built-in add -i/-p: update to latest iteration

compat/mingw.c
Our `mingw_*()` function family that works with sockets failed to set `errno`, as noticed in #2404.
=> Make sure `errno` is set when socket operations fail

add-interactive.c
https://github.com/gitgitgadget/git/pull/171 just made it into `next`, but in a slightly different form than is included in Git for Windows' `master`. This PR brings the latter up to date with the former.
=> Synchronize built-in add -i/-p patches with upstream

sequencer.c, t/t3430-rebase-merges.sh
As with many contributions accepted in Git for Windows' fork of Git, I shepherded this patch upstream, and happens frequently, I had to change a couple things in response to reviewer suggestions.
Let's "accept back" the version of the patch that made it already into `master` (see https://github.com/gitgitgadget/git/pull/327 for details).
=> Update ROGERSM94/fix-rebase to the version that made it upstream

compat/mingw.c, compat/mingw.h, t/t0060-path-utils.sh
This is a companion PR to https://github.com/gitgitgadget/git/pull/496 (including a merge commit needed to sort out merge conflicts with the `core.longPaths` feature).
On Windows, for historical reasons, file names such as `aux.c`, `nul.txt` are not allowed. For `aux.c`, attempts to write such a file will result in an obscure error, for `nul.txt` the call will succeed but no such file will appear, ever, instead the effect will be equivalent to writing to `/dev/null` on Linux/Unix.
Let's help users by refusing to create such files altogether, with an informative error message.
This addresses https://github.com/git-for-windows/git/issues/679 and supersedes https://github.com/git-for-windows/git/pull/686
=>  Refuse to write to reserved filenames

compat/mingw.c
This fixes the remaining part of https://github.com/git-for-windows/git/issues/1676, where working inside a Git worktree inside a symlinked directory would not work.
=> Do resolve symlinks in `getcwd()`

read-cache.c, t/t7415-submodule-names.sh, tree-walk.c
It was reported over in #2435 that the protections against file names containing backslashes (added as part of v2.24.1(2)) might be overzealous and we should instead only prevent them from being written to disk.
This commit does something slightly different, still: it prevents them from being added to the Git index (which is the staging area through which all remote commits go before they are written to disk).
=> Disallow writing, but not fetching commits with file names containing backslashes

git-gui/git-gui.sh
When dealing with submodule, the GIT_DIR might not be set. If it is not set
before, it cannot be unset and the execution ends with error:
can't unset "env(GIT_DIR)": no such element in array
Fix this by checking if GIT_DIR can be unset.
=> git-gui: fix GIT_DIR handling for submodules.

compat/vcbuild/scripts/clink.pl, contrib/buildsystems/engine.pl
=> Accommodate for vcpkg's upgrade to OpenSSL v1.1.x

add-interactive.c, t/t3701-add-interactive.sh
This PR intends to address https://github.com/git-for-windows/git/issues/2466.
=> Two fixes for the built-in `git add -i`

compat/mingw.c, t/t0060-path-utils.sh
This fixes https://github.com/git-for-windows/git/issues/2470.
=> Do not mistake `COM0` for a reserved file name

compat/mingw.c
In 1e64d18 (mingw: do resolve symlinks in `getcwd()`) a problem was
introduced that causes git for Windows to stop working with certain
mapped network drives (in particular, drives that are mapped to
locations with long path names). Error message was "fatal: Unable to
read current working directory: No such file or directory". Present
change fixes this issue as discussed in
https://github.com/git-for-windows/git/issues/2480
Signed-off-by: Bjoern Mueller <bjoernm@gmx.de>
Thanks for taking the time to contribute to Git!
Those seeking to contribute to the Git for Windows fork should see
http://gitforwindows.org/#contribute on how to contribute Windows specific
enhancements.
If your contribution is for the core Git functions and documentation
please be aware that the Git community does not …
=> mingw: fix fatal error working on mapped network drives on Windows

azure-pipelines.yml
Let's switch before [`vs2015-win2012r2` is turned off](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/) ;-)
=> Azure Pipeline: switch to the latest agent pools

compat/vcbuild/scripts/clink.pl
I don't remember having to do this in the past, so maybe something
changed with the libcurl distribution to cause the problem.  And ideally
I could send this upstream first rather than adding more ballast for GFW.
Update clink.pl to link with either libcurl.lib or libcurl-d.lib
depending on whether DEBUG=1 is set.
=> clink.pl: fix MSVC compile script to handle libcurl-d.lib

abspath.c, compat/mingw.c, compat/mingw.h, git-compat-util.h, t/t3700-add.sh
=> Handle `git add <file>` where <file> traverses an NTFS junction

ci/test-documentation.sh
Companion to https://github.com/git/git/pull/707
=>  Fix CI/PR failures in the "Documentation" job

compat/win32/fscache.c
This fixes the bug reported at #2494.
=> Fix a regression in the cooperation between FSCache and long paths

Makefile, compat/mingw.c, config.mak.uname, t/t0060-path-utils.sh
We still recommend running `git.exe` via the Git wrapper in `/cmd/`, just to make sure that the environment variables are set appropriately, such as adding the `/usr/bin/` directory to the `PATH`.
This is relevant e.g. for running the hooks via the Bash.
With this PR, we no longer _require_ that Git be run via the `/cmd/git.exe` wrapper: it can be run directly from `/mingw64/bin/git.exe`, configuring the environment variables appropriately itself (using the absence of the `MSYSTEM` variable as indicator that it should do so).
This addresses #2283
=> Allow running Git directly from `C:\Program Files\Git\mingw64\bin\git.exe`

credential.c
This fix makes using `git credentials` more friendly to Windows users. In previous version it was unable to finish input correctly without configuration changes (was tested in powershell, cmd, cygwin).
As we know credential filling should be finished by empty input, but
previous implementation does not take into account 'CLRF' ending, and hence instead of empty string we have '\r', which is interpreted as incorrect string.
So, this commit changes default reading function to more Windows compatible reading function.
Signed-off-by: Nikita Leonov nykyta.leonov@gmail.com
=> credential.c: fix credential reading for DOS systems

Documentation/config/http.txt, http.c
We [contributed a patch to cURL](https://github.com/curl/curl/pull/4981) to silently ignore certain errors during revocation checking.
This should help the problems e.g. with Fiddler or with corporate proxies where it is relatively common that certificates are missing CRL distribution point URLs.
Since this seems to be what the OpenSSL backend does by default, we force this to be the default for the Secure Channel backend, too (and it can be overridden via `http.schannelCheckRevoke`).
cc @niik
=> Introduce and use the new "best effort" strategy for Secure Channel revoke checking

compat/mingw.c
Even if the patch looks like it has nothing to do with cloning (or for that matter, with creating leading directories), this fixes https://github.com/git-for-windows/git/issues/2531.
=> Fix clone within a directory whose parent isn't readable by the current user

azure-pipelines.yml
This happens occasionally, and in those cases, it would appear that no fair amount of re-runs works around the issue.
=> ci: fix Visual Studio Build

compat/mingw.c
Microsoft introduced a new "Universal C Runtime Library" (UCRT) with
Visual Studio 2015. The UCRT comes with a new strftime() implementation that
supports more date formats. We link git against the older "Microsoft Visual C
Runtime Library" (MSVCRT), so to use the UCRT strftime() we need to load it from
ucrtbase.dll using DECLARE_PROC_ADDR()/INIT_PROC_ADDR().
Most supported Windows systems should have recieved the UCRT via Windows update,
but in some cases only MSVCRT might be available. In that case we fall back to
using that implementation.
=> mingw: use modern strftime implementation if possible

gitk-git/gitk
Running 'git rev-parse --show-toplevel' fails on a bare git repo.
This causes gitk to fail to startup.
Signed-off-by: Remy Bohmer <github@bohmer.net>
=> [fix] Gitk fails to open on a bare Git repository on Windows

compat/mingw.c
Update mingw_unlink() to first try to delete the file with existing
permissions before trying to force it.
Windows throws an error when trying to delete a read-only file.  The
mingw_unlink() compatibility wrapper always tries to _wchmod(666) the
file before calling _wunlink() to avoid that error.  However, since
most files in the worktree are already writable, this is usually
wasted effort.
Update mingw_unlink() to just call DeleteFileW() directly and if that
succeeds return.  If that fails, fall back into the existing code path
to update the permissions and use _wunlink() to get the existing
error code mapping.
=> mingw: improve performance of mingw_unlink()

config.mak.uname, contrib/buildsystems/Generators/Vcxproj.pm, t/t5505-remote.sh, t/t5516-fetch-push.sh
As can be seen [in this run](https://github.com/git-for-windows/git/runs/636383623?check_suite_focus=true), our current GitHub workflow does not play well with our `vs/master` branch: we commit `.vcxproj` files in directories named identically to the executables' names. This works on Windows because the executables actually have an additional `.exe` filename suffix. But on Linux/macOS, the compilation fails because they cannot write, say, `git`: there is already a directory under that name.
Let's fix this by renaming those directories, appending the suffix `.proj`. Oh, and work around `.git/branches/` problems (why exactly do we still create this directory?).
=> ci: avoid d/f conflict in vs/master

.github/workflows/main.yml
I did not think through how I designed the Windows job initializing the minimal subset of Git for Windows' SDK: it currently accesses Azure Blobs and uses way too much bandwidth, blowing right through my quota.
With this PR, we use the (slower) method of downloading the `git-sdk-64-minimal` Build Artifact of our Azure Pipeline again, which should fix that problem.
=> ci: avoid pounding on the poor ci-artifacts container

compat/mingw.c
This PR includes a single commit that fixes the `mingw_lstat` function to return correct size for symlinks on Windows. Prior to this commit the function returned a fixed size of 4096, which caused problems for repositories that were accessed using git from different platforms.
For example, if using both git for WSL and git for Windows the problem that I describe below could arise.
Consider a git repository accessed using git for WSL:
Now consider the same repository accessed using git for Windows:
Notice that `RelNotes`, which is a symbolic link, appears modified. This happened because `mingw_lstat` returned `st_size == 4096`, which then git for Windows compared to the index prepared by git for WSL and found a size mismatch.
Finally, using the commit in this PR, a patched `git-status.exe` …
=> mingw: lstat: compute correct size for symlinks

read-cache.c
Let's not mark symbolic links as modified _always_ when upgrading to v2.27.0: we can detect that situation and simply
pretend that a symbolic link with a known bad size was just checked it out, and therefore needs to be re-checked.
This will help people who upgrade from pre-v2.27.0 versions to post-v2.27.0 versions (but unfortunately not when upgrading to v2.27.0).
Cc: @billziss-gh
=> mingw: special-case index entries for symlinks with buggy size

compat/win32/fscache.c
This fixes https://github.com/git-for-windows/git/issues/2653
=> Fix `lstat()`'s `st_size` computation for symbolic links when FSCache is in effect

prompt.c
As of Git for Windows v2.27.0, there is an option to use Windows' newly-introduced Pseudo Console support. When running an interactive add operation with this support enabled, Git will receive CR/LF line
endings.
Therefore, let's not pretend that we are expecting Unix line endings.
This fixes https://github.com/git-for-windows/git/issues/2729
=> git add -i: handle CR/LF line endings in the interactive input

t/t7502-commit-porcelain.sh, wt-status.c
This PR attempts to resolve https://github.com/git-for-windows/git/issues/2623
Strip `cut_line[]` definition to enhance interoperability between UNIX and DOS line-ending styles
Signed-off-by: Luke Bonanomi <lbonanomi@gmail.com>
=> Rationalize line endings for scissors-cleanup

compat/mingw.c, t/t5601-clone.sh
=> Fix problem where clone adds core.worktree due to path case differences

builtin/diff-files.c, diff-lib.c, t/t2203-add-intent.sh, t/t7800-difftool.sh
This fixes https://github.com/git-for-windows/git/issues/2677
=> Fix `git difftool` with intent-to-add files

compat/vcbuild/README, compat/vcbuild/scripts/clink.pl, contrib/buildsystems/Generators/Vcxproj.pm, contrib/buildsystems/engine.pl
We currently see a lot of CI failures in the `vs-build` job. These issues are known, and already resolved upstream via the `os/vcbuild` branch. Let's backport that branch.
This is a companion PR to https://github.com/microsoft/git/pull/290
=>  Backport `os/vcbuild` to fix CI failures

builtin/clean.c, builtin/grep.c, compat/win32/fscache.c, diff.c, fast-import.c, mem-pool.c, mem-pool.h, quote.c, quote.h, read-cache.c, split-index.c, t/t7508-status.sh, wt-status.c
We need to resolve two conflicts that are not mere _merge conflicts_: the upstream changes to `quote_path()` and the `mem_pool` machineries require us to modify two of Git for Windows' own patches.
Of course, this PR really is _just_ an excuse to build yet another new [snapshot](https://wingit.blob.core.windows.net/files/index.html) so that we can test msys2-runtime-3.1.7-3.
=> Prepare for v2.29.0-rc0

compat/mingw.c
This is a fix for https://github.com/git-for-windows/git/issues/2802. It simply assumes that the console output code page is UTF-8.
This PR may very well also address https://github.com/git-for-windows/git/issues/1087 and https://github.com/git-for-windows/git/issues/1682, at long last.
=> fixup! mingw: ensure valid CTYPE

compat/mingw.c
Fixes https://github.com/git-for-windows/git/issues/2709
=> Ignore Vista+ HOMEDRIVE/HOMEPATH default for non-shell logons

.github/workflows/monitor-components.yml
I currently use private IFTTT Applets to get notified whenever a new version was released of a component bundled in Git for Windows.
There are two problems with that:
- This is totally opaque to the community
- IFTTT will stop supporting so many applets in their free plan
Let's use the power of GitHub workflows to address both issues.
=> Start monitoring updates of Git for Windows' component in the open

contrib/completion/git-prompt.sh
Resolves https://github.com/git-for-windows/git/issues/2799
=> Allow GIT_PS1_COMPRESSSPARSESTATE to be unset

t/t0014-alias.sh
trace on git for windows delivers extra info which makes test
'run-command formats empty args properly' fail:
$ cat actual.raw
10:49:28.858579 exec-cmd.c:237          trace: resolved executable dir: C:/git-sdk-64/mingw64/bin
10:49:28.872991 git.c:702               trace: exec: git-frotz a '' b ' ' c
10:49:28.872991 run-command.c:663       trace: run_command: git-frotz a '' b ' ' c
10:49:28.872991 run-command.c:663       trace: run_command: 'C:\git-sdk-64\mingw64\bin\busybox.exe' --help
git: 'frotz' ist kein Git-Befehl. Siehe 'git --help'.
sed delivers 2 lines back. increase the recognition string
=> t/t0014: fix: eliminate additional lines from trace

.github/workflows/monitor-components.yml
We had to start building our own versions of the i686 `gnutls` package. Let's get notified when we have to re-build.
=> Open tickets for new `gnutls` versions

git-mergetool--lib.sh, mergetools/bc
This fixes the issue where a user-supplied `bc4` difftool configuration was mishandled and would result in no tool to be shown, even if the exit status would suggest that everything is fine and dandy.
This fixes https://github.com/git-for-windows/git/issues/2893 and is a companion PR to https://github.com/gitgitgadget/git/pull/787.
=> difftool: support user-defined Beyond Compare setups correctly again

ci/print-test-failures.sh
This backports `jc/ci-github-set-env` (but not `js/ci-github-set-env`, because `whitespace.yml` has not been introduced into Git for Windows' `main` branch yet).
=> ci: avoid `set-env` construct in print-test-failures.sh

.github/workflows/main.yml, compat/bswap.h, compat/vcbuild/README, compat/vcbuild/vcpkg_copy_dlls.bat, compat/vcbuild/vcpkg_install.bat, contrib/buildsystems/CMakeLists.txt, contrib/buildsystems/Generators/Vcxproj.pm
Builds upon the work that was started in https://github.com/git-for-windows/git/pull/2507
I was able to build a Git executable for arm64 locally by doing some hacks/manual fixes. I can create artifacts as well, just can't run `git.exe` yet due to an error that `iconv-2.dll` is missing. To be continued 🚀 
Related to #2346
=> Windows arm64 support

t/t7522-status-show-ignored-directory.sh
As of v2.30.0-rc0, Git has a new `check-whitespace` workflow, and [it picked up on an issue](https://github.com/git-for-windows/git/runs/1553266276?check_suite_focus=true) that has been in Git for Windows for several ages. Let's address it.
=> Address a problem reported by the new `check-whitespace` workflow

.github/workflows/main.yml
This should shave off about 16 minutes off of our PR builds.
=> Use the pre-built vcpkg packages in the vs-build(arm64) job

contrib/buildsystems/CMakeLists.txt
Fixes https://github.com/git-for-windows/git/issues/2965
If you want to verify this yourself, please follow the steps from https://github.com/git-for-windows/git/pull/2915#issuecomment-739538291
=> Fix double .exe suffixes in CMakeLists.txt 

ci/install-dependencies.sh
We run "git pull" against "$cask_repo"; clarify that we are expecting not to have any of our own modifications and running "git pull" to merely update, by passing "--ff-only" on the command line.
Also, the "brew cask install" command line triggers an error message that says:
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
In addition, "brew install caskroom/cask/perforce" step triggers an error that says:
Error: caskroom/cask was moved. Tap homebrew/cask instead.
Attempt to see if blindly following the suggestion in these error messages gets us into a better shape.
[Merged directly from upstream's `jc/macos-install-dependencies-fix`]
=> ci/install-depends: attempt to fix "brew cask" stuff

t/t7422-submodule-long-path.sh
The `long-paths` tests need to be prepared for `js/default-branch-name-tests-final-stretch`: So far, the test script assumed the default branch name to be called `master`, but there are changes in upstream's `next` branch already that change that to `main` (at least as far as the test suite is concerned).
=> Prepare `long-paths` for upcoming upstream changes

.github/workflows/main.yml, contrib/buildsystems/CMakeLists.txt
Fixes https://github.com/git-for-windows/git/issues/2970 🎉 
With this PR, the DLLs are added correctly to the CMake build output:
=> cmake(install): include vcpkg dlls

.github/workflows/monitor-components.yml
`rss-issues-action` has some features to reduce the number of issues that we just close again without doing anything. Let's use them.
=> monitor-components: avoid opening unnescessary issues

.github/workflows/git-artifacts.yml
This workflow is a close transcription of [the Azure Pipeline we use to generate the official installer (and friends)](https://dev.azure.com/git-for-windows/git/_build?definitionId=34&_a=summary) since Git for Windows v2.25.1.
The idea is to let Git for Windows contributors generate those artifacts, without having to install _anything_ on their computer (except maybe Git for Windows, to modify the source code and to trigger the build).
With this, users can edit the file `.github/workflows/git-artifacts.yml` by uncommenting the `push:` line, push to their fork, and the artifacts will be generated and attached to the workflow run associated with the tip commit of the pushed branch.
Alternatively, users could [generate a Personal Access …
=> Add a GitHub workflow to generate Git for Windows' installer, portable Git, MinGit, etc

.github/workflows/main.yml
GitHub Actions is transitioning workflow steps that run on 'ubuntu-latest' from 18.04 to 20.04, which unfortunately does not have a `coccinelle` package yet. Let's use 18.04 for this job, then.
=> ci: pre-emptively fix the "static-analysis" job

.github/workflows/git-artifacts.yml
Adds the ARM64 artifacts to the `git-artifacts` GH Actions workflow 🚀 
Full run: https://github.com/dennisameling/git/actions/runs/537829979
One thing I noticed is that the ARM64 artifacts are significantly larger than the others. There might be some things we can enable on the MSVC-size to have it generate smaller binaries, but I'm not familiar enough with that toolchain to know how to do that.
=> git-artifacts: add ARM64 artifacts

contrib/buildsystems/CMakeLists.txt
For a couple of days now, all of Git for Windows' CI builds all fail in the `vs-build` jobs, while trying to configure the Visual Studio projects. The culprit is a recent change in `vcpkg`, and this PR fixes it.
cc @dennisameling (FYI)
=> cmake: work around recent `vcpkg` update

.github/workflows/git-artifacts.yml, contrib/buildsystems/CMakeLists.txt
The fact that `git-add.exe` (and over a hundred more commands) are still hard-linked in `libexec/git-core/` is more a historical than a useful thing. In particular when bundling MinGit, that's just useless weight, and we exclude it.
Except in the ARM64 variant, as it is built via `git-artifacts`, it does not work: our CMake-based build did not know how to exclude the dashed built-ins, and `mingit/release.sh` simply copies the entire ARM64 artifacts it was given, dashed built-ins or not.
Let's teach our CMake configuration to be helpful in this instance, by optionally skip those usually unwanted files.
=> Teach our CMake configuration to optionally skip hard-linking the dashed built-ins

.github/workflows/git-artifacts.yml
The `git-artifacts` workflow can be used to generate Git for Windows installers, MinGits, etc.
The improvements in this PR mostly revolve around two topics: actually make the ARM64 stuff work (it didn't work when I tried it), and accelerate the entire thing, mostly by using the shiny new [`setup-git-for-windows-sdk` GitHub Action](https://github.com/git-for-windows/setup-git-for-windows-sdk).
=> Assorted fixes/enhancements for the `git-artifacts` workflow

.github/workflows/git-artifacts.yml
Closes https://github.com/git-for-windows/git/issues/3015
Adds a workaround for Git Credential Manager Core to the `git-artifacts.yml` CI workflow, as discussed in https://github.com/git-for-windows/git/issues/3015#issuecomment-771585483
Test run in progress: https://github.com/dennisameling/git/actions/runs/617373202
=> git-artifacts: add workaround for GCM Core on ARM64

contrib/buildsystems/CMakeLists.txt
Closes https://github.com/git-for-windows/git/issues/3071
Currently, when Git for Windows is built with CMake, the `gitconfig` system-level file can't be read by Git. Because of this, things like `git clone` don't work correctly. More details in https://github.com/git-for-windows/git/issues/3071#issuecomment-789261386. This PR fixes that behavior by mimicking [what was already done in `config.mak.uname`](https://github.com/git-for-windows/git/blob/c1778565869b74b2c0ac225802a53f7b8a4133ec/config.mak.uname#L436-L440), but then slightly changed to work correctly with CMake.
Note: this applies to **all** CMake builds [where Windows is targeted](https://cmake.org/cmake/help/v3.0/variable/WIN32.html) (WIN32).
Before applying this PR:
```
denni@DESKTOP-8HTP3NV ARM64 /
$ git config --list …
```
=> cmake: set correct path to gitconfig on Windows

.github/workflows/git-artifacts.yml
We have moved and improved this logic to `build-extra` in https://github.com/git-for-windows/build-extra/pull/331. More details in that PR.
=> git-artifacts: Update ARM64 GCM Core workaround

.github/workflows/git-artifacts.yml, .github/workflows/main.yml
We now have the shiny new `get-azure-pipelines-artifact` GitHub Action to help us.
This is a companion PR to https://github.com/gitgitgadget/git/pull/879.
=> ci: cache vcpkg artifacts

.github/workflows/git-artifacts.yml
In skipped jobs, the `arm64/` directory does not exist, which would make this task fail: https://github.com/dscho/git/runs/2214202079?check_suite_focus=true
Cc: @dennisameling
=> git-artifacts: don't add ARM64-specific workaround for GCM Core in skipped jobs

compat/mingw.c
As reported in https://github.com/newren/git-filter-repo/pull/225, it looks like 99 bytes is not really sufficient to represent e.g. the full path to Python when installed via Windows Store (and this path is used in the hasb bang line when installing scripts via `pip`).
Let's increase it to what is probably the maximum sensible path size: 248 (the same as for `CreateDirectory()`).
=> mingw: allow for longer paths in `parse_interpreter()`

compat/mingw.c
Based on a work in https://github.com/git-for-windows/git/pull/3165 this makes parse_interpreter() inline with what lookup_prog() handles.
Even better way would be to use MAX_LONG_PATH and wchar_t instead of char to allow Unicode paths, but I don't have a proper testing environment at the moment, so this will do.
=> mingw: increase interpreter path length even further

Makefile, compat/vcbuild/find_vs_env.bat, compat/vcbuild/scripts/clink.pl, compat/vcbuild/scripts/rc.pl, config.mak.uname, contrib/buildsystems/Generators/Vcxproj.pm, contrib/buildsystems/engine.pl
This PR replaces https://github.com/git-for-windows/git/pull/3157
This addresses the various lurking bugs that we found in the MSVC=1 build
and fixes them first, creates a `rc.pl` script to wrap the `RC.EXE` commands
like we do for `CL.EXE`.  It then replays the existing `headless-git.exe` change 
and appends several fix-ups.  Finally, it adds some MSVC-specific cleanup (that
could really go first if that would be helpful).
To make it easier to figure out how to get this to build, I first reverted the
headless-git change and later replayed it.
I think this new series should replace the 
https://github.com/git-for-windows/git/commit/c13fa82dec4b053f742ec240e9af892e2c01d831
that you have stacked in `ready-for-upstream` (but I didn't touch the other commit in that thicket …
=> MSVC Fixups (redo of headless-git.exe)

.github/workflows/monitor-components.yml
The Action we used required over a minute (because it has to fetch a Docker container). I ported it to Javascript, and that Action runs much faster. Let's use it.
The most notable change is that the Javascript Action uses different (hopefully more intuitive) input names, and that the title filter is _inclusive_ rather than exclusive, i.e. feed items that match are converted to issues, not feed items that _don't_ match.
=> monitor-components: switch to a faster Action

CONTRIBUTING.md, SECURITY.md, compat/vcbuild/README
While rebasing Git for Windows onto v2.32.0-rc0, I noticed that the documentation was stale: `vs/master` (or more appropriately, `vs/main`) is no longer updated, and was deprecated in favor of using CMake already a long time ago.
=> Let the documentation reflect that there is no vs/master anymore

config.c
It does not make sense there, and it would spit out error messages.
=> fsmonitor: only enable it in non-bare repositories

fsmonitor-ipc.c
After upgrading to v2.32.0-rc2, I just ran `git rebase --autostash -i HEAD~2` and ran into a segmentation fault. Running this in the debugger reveals that v2 of the FSMonitor series introduced a `strlen(since_token)`, but `since_token` can be `NULL`.
It might look like an error to pass `NULL` here, but it is not because `write_packetized_from_buf_no_flush()` does not even attempt to look at that pointer if the number of remaining bytes to write is 0.
=> Fix segmentation fault in the FSMonitor v2 series

fsmonitor-ipc.c
I should have looked much more closely when crafting #3241: there was one other instance where `since_token` was not expected to be `NULL`: the Trace2 call. This only showed up in Scalar's Functional Tests because it created the situation where a new Git index is initialized (obviously, without a valid FSMonitor token) _and_ all of the Trace2 knobs are turned on.
=> FSMonitor v2: fix another fall-out of `since_token` being potentially `NULL`

builtin/fsmonitor--daemon.c, fsmonitor-ipc.c, fsmonitor.c
While Git's test suite did not report any regressions, I had to hunt for a few days to figure out why Scalar's Functional Tests were still unhappy with the new FSMonitor patch series.
This PR is the culmination of those efforts, and a sibling to https://github.com/microsoft/git/pull/371 (which not only integrates these patches, but makes sure that Scalar's Functional Tests are run in `microsoft/git` as part of the CI).
=> FSMonitor fixes

.github/workflows/monitor-components.yml
In our GitHub workflow that notifies us about new versions of important Git for Windows components, we already watch out for new GNU Privacy Guard versions. For v2.2.28, it became painfully clear, though, that this is not enough: we also have to build the GNU Privacy Guard dependencies `libgpg-error` and `libgcrypt` ourselves. So let's watch out for new versions of those libraries, too.
=> Monitor libgpg-error and libgcrypt versions

fsmonitor.c
In #3263, I fixed the issue where `fsmonitor_ipc__send_query()` was called with `NULL` as `last_token`, by simply not calling that function.
That works, but it is undesirable: it means that we do not even query the FSMonitor, and therefore do not get a token back, but instead store a dummy token and do a full scan. The next time we hit this code path, we do query the FSMonitor, but with a dummy token, and therefore cause _another_ full scan.
By instead calling that function with a dummy token right away we _do_ get back a valid token, and the second time we hit that code path we can reap the full benefit of the FSMonitor.
This is a companion of https://github.com/microsoft/git/pull/385.
=> Redo fix for FSMonitor

Documentation/config/http.txt, http.c
This adds support for a new http.sslAutoClientCert config value.
In cURL 7.77 or later the schannel backend does not automatically send
client certificates from the Windows Certificate Store anymore.
This config value is only used if http.sslBackend is set to "schannel",
and can be used to opt in to the old behavior and force cURL to send
client certificates.
This fixes #3292
=> http: Add support for enabling automatic sending of SSL client certificate

README.md
This adds a section in the `README.md` file, documenting the advice I gave privately to a few colleagues over the past few days (which made me realize that this institutionalized knowledge lives in only one brain so far, and this PR changes that).
=> Document how to build (and test) Git for Windows

pager.c
This works around https://github.com/git-for-windows/git/issues/3235 by _not_ setting `COLUMNS` when Git has no clue what the correct value should be.
=> Fix duplicated lines when scrolling in the pager

contrib/subtree/git-subtree.sh
This fixes https://github.com/git-for-windows/git/issues/3260.
=> Fix subtree on Windows

compat/fsmonitor/fsmonitor-fs-listen-win32.c
We used the `CreateFileA()` function which is susceptible to these vexing encoding problems: Windows has its own idea how to translate from non-wide characters to wide characters, and Git wants to always treat the non-wide characters as UTF-8.
This fixes https://github.com/git-for-windows/git/issues/3262
=> fsmonitor: handle non-ASCII characters in the git_dir/worktree paths

README.md
There is a neat, new feature, to open GitHub repositories quickly (remotely), and I think we should support it, too.
=> README: add an "Open in VS Code" badge

.github/workflows/git-artifacts.yml, .github/workflows/main.yml, contrib/buildsystems/CMakeLists.txt
Related to #3107
As reported by @rimrul in https://github.com/git-for-windows/git/issues/3083#issuecomment-791978513, `git version --build-options` returns the wrong CPU when building Git for ARM64 Windows.
Git's regular `Makefile` mentions that HOST_CPU should be defined when cross-compiling Git: https://github.com/git-for-windows/git/blob/37796bca76ef4180c39ee508ca3e42c0777ba444/Makefile#L438-L439
This is then used to set the GIT_HOST_CPU variable when compiling Git: https://github.com/git-for-windows/git/blob/37796bca76ef4180c39ee508ca3e42c0777ba444/Makefile#L1337-L1341
Then, when the user runs `git version --build-options`, it returns that value: https://github.com/git-for-windows/git/blob/37796bca76ef4180c39ee508ca3e42c0777ba444/help.c#L658
This PR adds the same functionality to the …
=> cmake(): allow setting HOST_CPU for cross-compilation

compat/mingw.c, t/t3400-rebase.sh, t/test-lib.sh
Fixes #2967 
When performing a rebase, `rmdir()` is called on the folder `.git/logs`. On Linux `rmdir()` exits without deleting anything in case `.git/logs` is a symbolic link but the Windows equivalent (`_rmdir`) does not behave the same and removes the folder if it is symlink which generates issues especially when Repo is used.
This commit updates `mingw_rmdir()` so that its behavior is the same as Linux `rmdir()` in case of symbolic links.
Some remarks:
* I asked confirmation to Microsoft about the actual behavior of `_rmdir()` with symlinks but I didn't get an answer yet so my conclusions are only based on what I saw while debugging on Windows 10 with Git Bash.
* I created a "rebase" test case because this problem was found initially when performing "git rebase" but in the end the …
=> rmdir: align behavior on Windows when called on symlinks

README.md
This was missed by the `check-whitespace` job (most likely because of issues that are being fixed in https://github.com/gitgitgadget/git/pull/995).
=> README: fix whitespace issue

ci/run-build-and-tests.sh, ci/run-test-slice.sh, contrib/subtree/Makefile
- Subtree tests run if (and only if) `make test` passes in Windows, Linux, and Mac build/test jobs
- For platforms that run `make test` more than once in `run-build-and-tests.sh`, subtree tests are only run after the _last_ execution of `make test`
- Added "fail fast" `exit 1` to `run-build-and-tests.sh` - otherwise, tests failing in `make test` wouldn't always fail the test execution (this might also be because I'm not _great_ at bash scripting 😉)
- `contrib/subtree` `test` target updated to invoke `t/` directory `all` target (rather than `test` target)
- Necessary to use the `$DEFAULT_TEST_TARGET`
- Matches root `test` target behavior
- CI execution with no failing tests is linked to this PR
- CI execution with forced failure in t0000: https://github.com/vdye/git/actions/runs/1102256177 …
=> Add `contrib/subtree` test execution to CI builds

.github/workflows/main.yml
This PR intends to merge early a fixup for my "speed up CI" work.
But in reality, it is only an excuse to get another snapshot so that folks can verify the fix for https://github.com/git-for-windows/git/issues/3368.
=> ci: use upload-artifacts v1 for dockerized jobs

compat/mingw.c
Over the course of the years, unfortunately a couple of build failures crept in, by squashing fixups (that were often necessitated by reordering commits/topics) into the wrong commits.
This PR tries to fix that, by merging in a couple of `fixup!` commits that target the correct commits instead.
Note: since the tip of the `main` branch _already_ compiles, some of these `fixup!` commits had to be done directly on top of the commits they want to be squashed into, and then they were merged on top of `main`.
The end result is _almost_ tree-same to `main`: only an extra forward declaration of `struct strbuf` is necessary. That's okay, though: it is good to have it, so that future reorganizations won't cause new build failures.
=> A couple of compile fixes

compat/mingw.c, git-compat-util.h
mingw-w64's pthread_unistd.h had a bug that mistakenly (because there is
no support for the *lockfile() functions required[1]) defined
_POSIX_THREAD_SAFE_FUNCTIONS and that was being worked around since
3ecd153a3b (compat/mingw: support MSys2-based MinGW build, 2016-01-14).
the bug was fixed in winphtreads, but as a sideeffect, leaves the
reentrant functions from time.h not longer visible and therefore breaks
the build.
since the intention all along was to avoid using the fallback functions,
formalize the use of POSIX by setting the corresponding feature flag and
to make the intention clearer compile out the fallback functions.
[1] https://unix.org/whitepapers/reentrant.html
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>
Thanks for taking the time to contribute to Git! …
=> mingw: avoid fallback for {local,gm}time_r()

builtin/pull.c, commit-graph.c
This is a tentative fix for https://github.com/git-for-windows/git/issues/3336.
=> git pull: release file handles to pack files before fetching

gpg-interface.c
It looks like we need to trim `\r` from the output of `ssh-keygen -Y find-principals`'s on Windows, or we end up calling `ssh-keygen -Y verify` with a bogus signer identity, as per screenshot. [ssh-keygen.c:2841](https://github.com/openssh/openssh-portable/blob/master/ssh-keygen.c#L2841) seems to confirm this hypothesis. Signature verification passes with the fix.
Apologies if this isn't the appropriate forum, and thank you for your work on Git for Windows!
-p.
=> gpg-interface: trim CR from ssh-keygen -Y find-principals

object-file.c, object-store.h, sha1dc_git.c, sha1dc_git.h, t/t1007-hash-object.sh
This short series starts the code conversion to the more portable `size_t` type for object sizes.
A minimalist test is used as the initial test case.
The Windows LLP64 convention and Linux LP64 conventions differ in the `sizeof(long)`,
meaning objects larger than 4GB (2GB in some case) are not handled correctly by the Linux LP64 code.
Git-LFS oversize object detection was resolved in Matt Cooper's series 596b5e77c9 (clean/smudge: allow clean filters to process extremely large files, 2021-11-02).
The strbuf's are already fully size_t in compatible.
Some RFC (request for comment) points:
- Brian Carlson for checking the wider SHAxxx compatibility (e.g. the other sha libraries)
- Dscho for the `>big` vs using a `$()` sub-shell for feeding the 5GB to stdin?
- Should test be in …
=> Begin `unsigned long`->`size_t` conversion to support large files on Windows

compat/mingw.c, compat/win32/flush.c, compat/win32/lazyload.h, compat/win32/trace2_win32_process_info.c, compat/winansi.c, t/helper/test-drop-caches.c
In i686 builds, this will crash with a segmentation fault:
```sh
git log --date='format:%Y-%m-%d %H:%M' --pretty='format:%cd'
```
(Note that if you try to reproduce this in a regular Git for Windows SDK, you will have to call `make NDEBUG=1` to be able to reproduce the segmentation fault.)
The reason is that the `strftime()` function is imported with an incorrect calling convention. It is _quite_ timely that Matthias Aßauer submitted [a patch](https://github.com/git/git/pull/1181) to address precisely this bug, and that contribution already made it into upstream's `seen` branch as the `ma/windows-dynload-fix` topic (and is [slated to be fast-tracked into v2.35.0](https://lore.kernel.org/git/nycvar.QRO.7.76.6.2201111412300.1081@tvgsbejvaqbjf.bet/)). This PR backports that topic, along with …
=> Fix custom date formats in i686 builds

.github/workflows/git-artifacts.yml
Some clean-ups based on running the workflow definition through https://rhysd.github.io/actionlint/
=> git-artifacts: remove stale outputs

compat/win32/fscache.c
This fixes https://github.com/git-for-windows/git/issues/3674.
=> Fix "BUG: refs/files-backend.c:465: returning non-zero -1, should have set myerr!"

compat/win32/fscache.c
As per https://devblogs.microsoft.com/commandline/per-directory-case-sensitivity-and-wsl/, it is possible to turn on case-sensitivity on a directory-by-directory basis. While Git is not really prepared for the situation that a worktree has some directories where filenames are case-sensitive and other where filenames are case-insensitive, Git should at least handle the case where the worktree has filename case-sensitivity turned on in its entirety. This actually works!
Except for FSCache. Which was [reported as a bug](https://github.com/git-for-windows/git/issues/3686), and which this here PR seems to fix.
=> Teach FSCache about case-sensitive filenames

.github/workflows/git-artifacts.yml
While this is needed to future-proof the `git-artifacts` workflow, it is not crucial to Do It Right Now. However, it presents a perfect excuse to build a new [snapshot](https://wingit.blob.core.windows.net/files/index.html) once [v3.3.4 of the MSYS2 runtime has been built](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=94421&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a).
=> fixup! Add a GitHub workflow to generate Git for Windows' Pacman package

builtin/rebase.c
Hi,
This small update to the die() preserve-merges messages is a response to the reported edge case in the Git-for-Windows [googlegroups thread ](https://groups.google.com/g/git-for-windows/c/3jMWbBlXXHM) where even `git rebase --continue` would die.
The `preserve` option is still offered in the latest editions of Visual Studio (*), despite being deprecated for a long time, so the potential for unfamiliar users to fall into the same possible traps of running a pull-preserve (then with conflicts) on mixed Git versions could still occur. E.g. if the repo is on a network drive, and different users, with different Git versions collaborate on fixing conflicts. 
Let's beef up the die messages to point users toward these resolutions.
(*) I have logged a [feedback …
=> Update the die() preserve-merges messages to help some users

fsmonitor-settings.c
I noticed this a few times but was not able to come up with an easy way to trigger it, but I _think_ the code is obviously correct 😄
=> Try to advise about core.useBuiltinFSMonitor's deprecation only once

fsmonitor-settings.c
This change to warn about core.useBuiltinFSMonitor is a good one, but it
is too aggressive. If a user has set core.useBuiltinFSMonitor=false,
then that warning shows up.
Perhaps there is value in warning users that their explicit disabling of
the feature will stop working. However, VFS for Git does this
assignment, so all users on those enlistments will start getting
warnings after upgrading Git. This situation is probably much more
likely than a typical user disabling the experimental feature
themselves.
Putting in this fix is easier than rereleasing VFS for Git.
=> fixup! fsmonitor: reintroduce core.useBuiltinFSMonitor

path.c
After attempting to add directory on a network share to the `safe.directory` configuration with, for example:
```
git config --global --add safe.directory //servername/repos/myrepo
```
The warning about an outdated path style:
```
warning: encountered old-style '//servername/repos/myrepo' that should be '%(prefix)//servername/repos/myrepo'
```
However, the warning is missing a trailing `/` behind the prefix.
This PR fixes the warning such that the resulting configuration works.
Also see https://stackoverflow.com/a/71859164/4473230
Closes #3786
=> Include trailing slash in prefix migration instructions

Documentation/config/safe.txt, compat/mingw.c, setup.c, t/t0033-safe-directory.sh
The first three commits are rebased versions of those in gitgitgadget/git#1215. These allow the following:
1. Fix `git config --global foo.bar <path>` from allowing the `<path>`. As a bonus, users with a config value starting with `/` will not get a warning about "old-style" paths needing a "`%(prefix)/`".
2. When in WSL, the path starts with `/` so it needs to be interpolated properly. Update the warning to include `%(prefix)/` to get the right value for WSL users. (This is specifically for using Git for Windows from Git Bash, but in a WSL directory.)
3. When using WSL, the ownership check fails and reports an error message. This is noisy, and happens even if the user has marked the path with `safe.directory`. Remove that error message.
=> Various fixes around `safe.directory`

compat/mingw.c
@dscho @phil-blain @rimrul 
Hi guys, this is half of my fix for #3629.
Once this is done I will try to fix quoting/escaping in `$env:EDITOR` which was the other problem there.
=> mingw: set $env:TERM=xterm-256color for newer OSes

contrib/buildsystems/CMakeLists.txt
At least in systems where the user is local and not an administrator
git will install in a subdirectory of %APPDATALOCAL%, so it makes
sense to also look there for the shell needed by the cmake integration
with Visual Studio.
=> cmake: support local installations of git

fsmonitor-settings.c
The phrasing confused some users to believe that the built-in FSMonitor was deprecated altogether. Let's try to clear that up.
=> Adjust the core.useBuiltinFSMonitor deprecation warning to make clearer

.github/ISSUE_TEMPLATE.md
PowerShell does not understand the Command Prompt `%ENV_VAR%` syntax, it
uses `$env:ENV_VAR` instead. Offer such an invocation to the reader in
the "What options did you set as part of the installation" question.
=> .github/ISSUE_TEMPLATE.md: add PowerShell syntax for install options

.github/workflows/monitor-components.yml
Since PCRE2 moved to GitHub, we can use our regular workflow to monitor for PCRE2 updates, too.
Previously, we used https://github.com/git-for-windows/track-website-changes for that (scraping the website, which is actually out of date right now, still showing v10.39).
=> monitor-components: track PCRE2, too

Documentation/RelNotes/2.36.1.txt, GIT-VERSION-GEN, RelNotes
A recent update of GCC in Git for Windows' SDK (a subset of which is used in Git's CI/PR builds) broke the build. Lets' fix it.
This is a companion of https://github.com/gitgitgadget/git/pull/1238.
=> ci: fix `windows-build` with GCC v12.x

compat/winansi.c
NtQueryObject under Wine can return a success but fill out no name.
In those situations, Wine will set Buffer to NULL, and set result to
the sizeof(OBJECT_NAME_INFORMATION).
Running a command such as
echo "$(git.exe --version 2>/dev/null)"
will crash due to a NULL pointer dereference when the code attempts to
null terminate the buffer, although, weirdly, removing the subshell or
redirecting stdout to a file will not trigger the crash.
Alternatives include checking Buffer itself, however, I am not sure
what is the official behavior of the function due to a lack of
documentation.
Another alternative is to check the Length field, but similar to above,
I do not know what the official behavior is.
This code is based on the behavior of NtQueryObject under wine and
reactos.
Signed-off-by: …
=> winansi: check result before using Name for pty

.github/workflows/git-artifacts.yml
We recently fixed this in the `setup-git-for-windows-sdk` Action, but only in v1. We shouldn't use v0 anymore, anyway.
While at it, reword the commit message because that Action is not exactly shiny new anymore.
=> git-artifacts: fix the time-out while trying to set up the Git for Windows SDK

parallel-checkout.c
This actually targets the parallel checkout that is not parallel, which is the case when not enough work is to be done to justify fanning out into multiple workers.
This addresses https://github.com/git-for-windows/git/issues/3904
=> Fix parallel checkout with FSCache

Documentation/config.txt, Documentation/config/windows.txt, compat/mingw.c
Signed-off-by: sunzhuoshi <sunzhuoshi@gmail.com>
=> Fix append failure issue under remote directories #2753

compat/mingw.c, setup.c
Since FAT cannot store ownership information, users cannot do anything about "unsafe ownership" there. Except exempt the directory via the `safe.directory` mechanism. Inform the users about this (rather than the bogus "World owns this" message).
Since we cannot know at the time the ownership check is performed whether Git will require a valid repository or not, we keep mum in the general case, and only say something if the `GIT_TEST_DEBUG_UNSAFE_DIRECTORIES` knob is on.
Speaking of that knob, we now hint to the users that they can use this knob to find out more, in case that the ownership fails (and Git absolutely requires a valid repository).
This addresses https://github.com/git-for-windows/git/issues/3886
=> Offer more details to users about the ownership check on FAT32

Documentation/git-status.txt, builtin/commit.c, t/t7508-status.sh
This option was quite contentious and we were only able to get it into core Git in a very different form:
```sh
git --no-optional-locks status
```
To help Git for Windows users off of the `--no-lock-index` option, we re-added it and deprecated it.
Now is the time to drop it.
This PR should be applied *after* https://github.com/git-for-windows/git/pull/2067
=> Drop deprecated `git status --no-lock-index` option

mergetools/vimdiff
This fixes https://github.com/git-for-windows/git/issues/3945
=> mergetool(vimdiff): allow paths to contain spaces again

mergetools/vimdiff
Whoops. The final version that made it into upstream had this change, but I forgot to include it when opening [the Git for Windows PR](https://github.com/git-for-windows/git/pull/3960)... 
Technically, it is not all that crucial to get this fixup into Git for Windows, but it provides a fine excuse for building a new [snapshot](https://wingit.blob.core.windows.net/files/index.html) that includes Bash v5.1...
=> fixup for the vimdiff regression tests

config.mak.uname
Whith Windows 2000, Microsoft introduced a flag to the PE header to mark executables as
"terminal server aware". Windows terminal servers provide a redirected Windows directory and
redirected registry hives when launching legacy applications without this flag set. Since we
do not use any INI files in the Windows directory and don't write to the registry, we don't
need  this additional preparation. Telling the OS that we don't need this should provide
slightly improved startup times in terminal server environments.
When building for supported Windows Versions with MSVC the /TSAWARE linker flag is
automatically set, but MinGW requires us to set the --tsaware flag manually.
This partially addresses https://github.com/git-for-windows/git/issues/3935
=> MinGW: link as terminal server aware

compat/mingw.c
This fix for the issue : https://github.com/git-for-windows/git/issues/3727
Use case :
Creation of a tag in the form "parent/child".
Exemple :
> git tag -a -m "my message" tagdir/mytag
Context :
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.2565]
Error :
fatal: cannot lock ref 'refs/tags/tagdir/mytag': unable to resolve reference 'refs/tags/tagdir/mytag': Not a directory
Problem analysis:
GetFileAttributesExW used in mingw_lstat function in git/compat/mingw.c can raise an error ERROR_PATH_NOT_FOUND.
In this case, the has_valid_directory_prefix is used to check if the …
=> Fix when lazy caching of network shares tags directories were just created with previously-unhandled attributes

Makefile, compat/mimalloc/LICENSE, compat/mimalloc/alloc-aligned.c, compat/mimalloc/alloc.c, compat/mimalloc/arena.c, compat/mimalloc/bitmap.c, compat/mimalloc/bitmap.h, compat/mimalloc/heap.c, compat/mimalloc/init.c, compat/mimalloc/mimalloc-atomic.h, compat/mimalloc/mimalloc-internal.h, compat/mimalloc/mimalloc-types.h, compat/mimalloc/mimalloc.h, compat/mimalloc/options.c, compat/mimalloc/os.c, compat/mimalloc/page-queue.c, compat/mimalloc/page.c, compat/mimalloc/random.c, compat/mimalloc/readme.md, compat/mimalloc/segment-cache.c, compat/mimalloc/segment.c, compat/mimalloc/stats.c, compat/win32/pthread.c, compat/win32/pthread.h, config.mak.dev, config.mak.uname, git-compat-util.h
As per [the very author of `nedmalloc`](https://github.com/ned14/nedmalloc/issues/20#issuecomment-343432314), "nedmalloc is pretty much EOL". In other words, it is unmaintained since 2014.
Nevertheless, we rely on `nedmalloc` in Git for Windows because the MINGW toolchain is stuck with an MSVC runtime that comes with a `malloc()` implementation that is not quite up to par.
I tested [with `git repack -q -d -l -A --unpack-unreachable=2.weeks.ago` in a partial clone of the Linux source code](https://github.com/dscho/git/actions/runs/2859581320), which seems to exercise the `malloc()` function a lot. Here is the table for the `gcc` builds:
| | MIMALLOC | MIMALLOC2 | DEFAULT | NEDMALLOC|
|-- | -- | -- | -- | --|
|run `#1` | 943.426 | 968.415 | 994.807 | 995.383|
|run `#2` | 978.5 | 970.002 | …
=> Switch Git for Windows to using mimalloc instead of nedmalloc

Makefile
The CI builds have been seriously broken as of v2.38.1 by the constantly failing `linux-leaks` job. Let's backport the work-around that has been applied to upstream Git (but that funnily has not been based directly on top of v2.38.1).
=> ci: fix the `linux-leaks` job

.github/workflows/clangarm64-build.yml, compat/bswap.h, config.mak.uname
**This requires an ARM64-machine with Windows 11 installed (which supports x64 emulation for MSYS2)**
This is basically a successor of #3427 but stays _very_ close to Git for Windows's SDK and integration with MSYS2. Thanks to the work the MSYS2 team did on `clangarm64`, this actually becomes very easy to do now!
- Use the main MSYS2/git-sdk-64 setup, which works on Windows 11 on ARM thanks to x64-emulation
- Configure the official `clangarm64` MSYS2 repo
- Install `mingw-w64-clang-aarch64-toolchain` which contains the ARM64-native Clang compiler
Successful CI run on my ARM64 machine: https://github.com/dennisameling/git/actions/runs/2557291542. The `make -j8` command took 3m9s on my machine, which I think is very decent.
Just to be 100% clear that the compiler itself is indeed …
=> Add support for CLANGARM64 target

.gitignore, Makefile, contrib/buildsystems/CMakeLists.txt, t/t0060-path-utils.sh, t/test-lib.sh
When building Git via Visual Studio and then running the tests via CTest (which is made very easy by Visual Studio), there are test failures. This PR intends to address those.
This closes #3966
=> Fix CTest failures

compat/mimalloc/os.c
The `GetNumaProcessorNode()` symbol is not defined in Nano Server's DLLs (because that function is long deprecated). This caused Git no longer to work on Nano Server.
Instead of importing it statically, try to import it dynamically, and fall back gracefully if it cannot be loaded.
This fixes https://github.com/git-for-windows/git/issues/4052
=> mimalloc: allow running in Windows Nano Server containers

.github/workflows/monitor-components.yml
We also need to monitor libfido2 (and its dependency libcbor) because that library is responsible for support of security keys in OpenSSH, e.g. making it work with Windows Hello.
=> monitor-updates: add libfido2 and libcbor

.github/workflows/monitor-components.yml
The `monitor-components` workflow's purpose is to notify the Git for Windows maintainers when new package versions are published and may need to be integrated into Git for Windows.
This PR brings two improvements to this workflow:
- We now explicitly disable the workflow everywhere but the Git for Windows fork of Git, instead of relying on scheduled workflows being disabled in forks (of the fork) by default.
- The label and the URL of the Git Credential Manager part was fixed. I noticed that the label was wrong when https://github.com/git-for-windows/build-extra/pull/451 was opened but failed to mention that it would close the issue (https://github.com/git-for-windows/git/issues/4166)
=> Two `monitor-components` fixes

repository.c
It is checked for w.r.t. global repository struct down in the callstack in compatibility layer for MinGW before being assigned in the function that `free()`'d it.
=> Fix global repository field not being cleared

Makefile
When compiling in non-DEVELOPER mode, we currently do not suppress any warnings about the mimalloc code. And there are [a ton of them](https://dev.azure.com/git-for-windows/git/_build/results?buildId=111244&view=logs&j=31a7ecae-43f3-5669-2a92-3fc5c046b795&t=2b55ac6e-fb99-5b86-1bfa-7cc690d62aa6&l=1592).
Since none of them point out critical mistakes in the code, and since mimalloc is an upstream project, we already suppress these warnings in DEVELOPER mode. Let's suppress even the ones that only appear in non-DEVELOPER mode.
=> mimalloc: suppress some non-critical compiler warnings (or: prepare for v2.39.0(2))

INSTALL, git-curl-compat.h, http-push.c, http.c, http.h, remote-curl.c
This fixes the `linux-musl` and `osx-gcc` jobs which [started](https://github.com/git-for-windows/git/actions/runs/3985792568/jobs/6833602370) to [fail](https://github.com/git-for-windows/git/actions/runs/3985792568/jobs/6833601563).
=> Address deprecated curl APIs

compat/mingw.c, t/t0060-path-utils.sh
This PR fixes a pretty fundamental problem where `win32_strbuf_realpath()` mishandled non-existing paths that are close to the drive root, e.g. `C:/foo`.
This fixes https://github.com/git-for-windows/git/issues/4200
=> Fix Windows-specific problem to determine the real path near a drive root

config.mak.uname
It is merely a historical wart that, say, `git-commit` exists in the `libexec/git-core/` directory, a tribute to the original idea to let Git be essentially a bunch of Unix shell scripts revolving around very few "plumbing" (AKA low-level) commands.
Git has evolved a lot from there. These days, most of Git's functionality is contained within the `git` executable, in the form of "built-in" commands.
To accommodate for scripts that use the "dashed" form of Git commands, even today, Git provides hard-links that make the `git` executable available as, say, `git-commit`, just in case that an old script has not been updated to invoke `git commit`.
Those hard-links do not come cheap: they take about half a minute for every build of Git on Windows, they are mistaken for taking up huge amounts of …
=> Skip linking the "dashed" `git-<command>`s for built-ins

ARCHITECTURE.md
The Git for Windows project has grown quite complex over the years, certainly much more complex than during the first years where the msysgit.git repository was abusing Git for package management purposes and the git/git fork was called 4msysgit.git.
Let's describe the status quo in a thorough way.
=> Describe Git for Windows' architecture

.github/workflows/monitor-components.yml
The `GitCredentialManager` GitHub organization has been renamed to `git-ecosystem`. See [1]. While the old URL currently still works, it's better to update to the current URL.
[1] https://github.com/git-ecosystem/git-credential-manager/pull/1141
=> fixup! Add a GitHub workflow to monitor component updates

contrib/buildsystems/CMakeLists.txt
Even if CMake is not the canonical way to build Git for Windows, but CMake support merely exists in Git to support building Git for Windows using Visual Studio, we should include `headless-git` in such a scenario when installing the binaries to a given location.
=> cmake: install headless-git.

git-gui/git-gui.sh
This is a companion PR of https://github.com/prati0100/git-gui/pull/95
Since Git v2.39.1, we are a bit more stringent in searching the PATH. In particular, we specifically require the `.exe` suffix.
However, the `Repository>Explore Working Copy` command asks for `explorer.exe` to be found on the `PATH`, which _already_ has that suffix.
Let's unstartle the PATH-finding logic about this scenario.
This fixes https://github.com/git-for-windows/git/issues/4356
=> Git GUI: fix Repository>Explore Working Copy

path.c
Once upon a time, Git for Windows had the need to specify paths in the config that are relative to the runtime prefix (i.e. relative to the location where Git for Windows happens to be installed). To support that, special handling was introduced to treat paths starting with a forward slash as relative to the runtime prefix. When trying to upstream this feature, it was determined that it is not portable enough, and it was deprecated in favor of the new strategy: starting paths with `%(prefix)/` would indicate that they are relative to the runtime prefix.
After deprecating the "leading slash means relative to runtime prefix" feature in v2.34.0 (released November 15th, 2021), it is time to drop it. This reverts commit 28fdfd8a4183 and addresses …
=> Drop the old-style runtime-prefix handling in `interpolate_path()`

Makefile, compat/lazyload-curl.c, config.mak.uname
As per https://github.com/git-for-windows/git/issues/4350#issuecomment-1485041503, the major block for upgrading Git for Windows' OpenSSL from v1.1 to v3 is the tricky part where such an upgrade would break `git fetch`/`git clone` and `git push` because the libcurl depends on the OpenSSL DLL, and the major version bump will _change_ the file name of said DLL.
To overcome that, the plan is to build libcurl flavors for each supported SSL/TLS backend, aligning with the way MSYS2 builds libcurl, then switch Git for Windows' SDK to the Secure Channel-flavored libcurl, and teach Git to look for the specific flavor of libcurl corresponding to the `http.sslBackend` setting (if that was configured).
Here is the PR to teach Git that trick.
=> Lazy load libcurl, allowing for an SSL/TLS backend-specific libcurl

GIT-VERSION-GEN
Seems that we're being hit by a test failure due to too-stringent assumptions on Git's part about cURL's error messages.
=> Backport CI fix

.github/workflows/nano-server.yml, Documentation/config/core.txt, compat/mingw.c, compat/win32/fscache.c, compat/win32/wsl.c, compat/win32/wsl.h, config.mak.uname, contrib/buildsystems/CMakeLists.txt
In WSL(2), we can set the mode for an NTFS file, for example:
$ chmod 0755 /mnt/d/test/a.sh
provided that WSL has enabled metadata mounting NTFS volumes.
In order to facilitate better collaboration between the Windows
version of Git and the WSL version of Git, we can make the Windows
version of Git also support reading and writing NTFS file modes
in a manner compatible with WSL.
In this pull request, I've incorporated two commits. The initial commit
introduces two helper functions for reading and writing file mode bits.
The subsequent commit enhances Git with WSL compatibility for
improved collaboration.
=> [NEW FEATURE] make git-for-windows supports posix file mode bits in WSL's way

compat/mingw.c
OK, having another go at making a clean PR for this.
=> Reset READONLY if rename fails

compat/mingw.c
Another (hopefully clean) PR for showing the error warning about atomic append on windows after failure on APFS, which returns EBADF not EINVAL.
Signed-off-by: David Lomas <dl3@pale-eds.co.uk>
=> Additional error checks for issuing the windows.appendAtomically warning

compat/lazyload-curl.c
For historical reasons, the Win32 API provides `*A()` and `*W()` versions of many functions, e.g. `LoadLibraryExA()` and `LoadLibraryExW()`. The difference between these two function families is that the latter works on wide-character Unicode strings while the former accepts localized single- and multi-byte character sequences.
In Git for Windows's source code, we should not use the `*A()` family of functions at all because we use UTF-8 internally, which is not typically the current locale, and therefore the `*A()` functions will most often do unintended things. However, that's exactly what I did in https://github.com/git-for-windows/git/pull/4410: using `LoadLibraryExA()` (I do not remember why, but can guess that I used it for testing and intended to replace it with the `*W()` …
=> Load `libcurl-4.dll` correctly even when there are umlauts in its absolute path

compat/mingw.c, t/t2031-checkout-long-paths.sh
Git for Windows does not handle symbolic links correctly when their target is an absolute path without a drive prefix: a drive prefix is added.
These type of paths, however, are completely legitimate on Windows, they are _kind of_ absolute paths, as they are still relative to the current directory's drive. So let's handle them as intended: by ensuring that targets that have no drive prefix _before_ normalization still don't have a drive prefix _after_ normalization.
Oddly enough, the code that needs to be patched seems to have nothing to do with symbolic links, but all with long paths. Yet this is precisely the code path taken by `win32_create_symlink()` that adds that drive prefix (via normalization). The reason why only symbolic links seem to be affected is that this is the only usage …
=> When looking at potentially long paths: leave drive-less absolute paths intact

http.c
HTTP Header redaction code has been adjusted for a newer version of cURL library that shows its traces differently from earlier versions.
This is purely a fix for Git's test suite, no Git behavior is actually changed by this PR, read: it has no user-visible changes.
This PR is a close relative of https://github.com/microsoft/git/pull/609.
=> Backport fix for t5559.{18,19,39}

.github/workflows/monitor-components.yml
We've switched from p7zip to regular 7-Zip recently. With that we don't need to monitor p7zip for updates anymore, but we want to stay informed about 7-Zip updates now. Change the feed accordingly. Since the new feed contains 15 different files as separate items for the latest 7-Zip update, aggregate them into a single issue.
=> monitor-components: switch from p7zip to regular 7-Zip

.github/workflows/monitor-components.yml
after merging https://github.com/git-for-windows/MINGW-packages/pull/75 we'll want to be notified when Msys2 updates their mingw-w64-clang package.
=> monitor components: monitor mingw-w64-clang

compat/winansi.c
Windows 10 version 1511 (also known as Anniversary Update), according to https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences introduced native support for ANSI sequence processing. This allows using colors from the entire 24-bit color range.
All we need to do is test whether the console's "virtual processing support" can be enabled. If it can, we do not even need to start the `console_thread` to handle ANSI sequences.
Incidentally, this addresses https://github.com/git-for-windows/git/issues/3712.
=> win32: use native ANSI sequence processing, if possible

INSTALL, git-curl-compat.h, http.c, remote-curl.c
As discussed [here](https://github.com/git-for-windows/git/issues/4883#issuecomment-2045393711), we should have a work-around in place before deploying libcurl 8.7.1.
=> libcurl 8.7 regression workaround

CODE_OF_CONDUCT.md, README.md
Version 2.1 of the [Contributors Covenant](https://www.contributor-covenant.org/) was released already almost 3 years ago. Better integrate it late than never.
Having an enforced Code of Conduct [is more important than ever](https://www.404media.co/xz-backdoor-bullying-in-open-source-software-is-a-massive-security-vulnerability/).
While at it, adapt it more to the needs of Git for Windows.
=> Update the Code of Conduct

compat/regex/regcomp.c, compat/regex/regex_internal.c, compat/regex/regexec.c, git-compat-util.h
The GCC v14.1 upgrade broke the build of `git-artifacts`. Partially, this has been fixed upstream already, but the i686 build requires a separate fix.
This addresses #4953.
=> Fix build with GCC v14.1

compat/winansi.c
In #4700, I introduced a change in Git for Windows' behavior where it would favor recent Windows 10 versions' native ANSI sequence processing to [Git for Windows' home-grown one](https://github.com/git-for-windows/git/blob/v2.45.1.windows.1/compat/winansi.c#L362-L439).
What I missed was that the home-grown processing _also_ ensured that text written to the Win32 Console was carefully converted from UTF-8 to UTF-16 encoding, while the native ANSI sequence processing would respect the currently-set code page.
However, Git for Windows does not use the current code page at all, always using UTF-8 encoded text internally. So let's make sure that the code page is `CP_UTF8` when Git for Windows uses the native ANSI sequence processing.
This fixes …
=> Use UTF-8 code page when using native ANSI sequence processing

.github/workflows/monitor-components.yml
MSYS2 [renamed the mingw-w64-clang folder to mingw-w64-llvm](https://github.com/msys2/MINGW-packages/commit/2ad570ca96fbb35cc408763f1a4d421801466fb8), adjust the monitor-components workflow accordingly.
=> Adjust monitor-components workflow for new mingw-w64-clang name

compat/mingw.c
Companion to https://github.com/gitgitgadget/git/pull/1752.
This (hopefully) addresses https://github.com/git-for-windows/git/issues/5016.
=> mingw: drop bogus (and unneeded) declaration of `_pgmptr`

.github/workflows/monitor-components.yml
Let's also keep an eye out for new InnoSetup versions, as we rely on using reasonable secure versions of it.
=> monitor-components: add InnoSetup

path.c
=> Fallback to AppData if XDG_CONFIG_HOME is unset

compat/win32/path-utils.c, compat/win32/path-utils.h, git-compat-util.h, run-command.c
Git LFS is now built with Go 1.21 which no longer supports Windows 7. However, Git for Windows still wants to support Windows 7.
Ideally, Git LFS would re-introduce Windows 7 support until Git for Windows drops support for Windows 7, but that's [not going to happen](https://github.com/git-for-windows/git/issues/4996#issuecomment-2176152565).
The next best thing we can do is to let the users know what is happening, and how to get out of their fix, at least.
This is not quite as easy as it would first seem because programs compiled with Go 1.21 or newer will simply throw an exception and fail with an Access Violation on Windows 7.
The only way I found to address this is to replicate the logic from Go's very own `version` command (which can determine the Go version with which a given …
=> run-command: be helpful when Git LFS fails on Windows 7

compat/win32/path-utils.c
In commit git-for-windows/git@46d14a6f7189a604a0812b143dc5c51488a01895 of PR git-for-windows/git#5042 the `wait_or_whine()` function in `run-command.c` was revised to [call](https://github.com/git-for-windows/git/blob/b105301ef9107c8c2980a24eca89a2992a1c074b/run-command.c#L571) a new function in the case where an executable fails to run, to check whether this was caused by a Git LFS binary compiled with a version of the Go language that no longer supports Windows 7. This change was made to address the issue reported in git-for-windows/git#4996.
The new function, `win32_warn_about_git_lfs_on_windows7()`, [performs](https://github.com/git-for-windows/git/blob/b105301ef9107c8c2980a24eca89a2992a1c074b/compat/win32/path-utils.c#L226-L232) several initial checks to test whether the failed …
=> run-command: refine Git LFS check on Windows 7

Documentation/Makefile, Documentation/docinfo.html
Since 76880f0510c (doc: git-clone: apply new documentation formatting guidelines, 2024-03-29), the synopsis of `git clone`'s manual page is rendered differently than before; Its parent commit did the same for `git init`.
The result looks quite nice. When rendered with AsciiDoc, that is. When rendered using AsciiDoctor, the result is quite unpleasant to my eye, reading something like this:
SYNOPSIS
git clone
[
--template=
<template-directory>]
[
-l
] [
-s
] [
--no-hardlinks
] [
-q
] [
[... continuing like this ...]
Even on the Git home page, where AsciiDoctor's default stylesheet is not used, this change results in some unpleasant rendering where not only the font is changed for the `<code>` sections of the synopsis, but padding and a different background color make the visual impression …
=> asciidoctor: fix `synopsis` rendering

compat/win32/fscache.c
Support for wsl mode bits was previously added to git, but there was a bug because the filenames provided by fscache did not contain paths.
This commit fixes the issue.
The previous feature is added in PR #4438,
but at that time I didn't tested so much.
Sorry to have this bug.
To test this feature, set core.wslcompat to ture and core.filemode to true and make sure repo is on NTFS.
=> [bugfix] fix wsl mode bits error in subdir

.github/workflows/main.yml
The `linux32` jobs are seeing this error:
Error: This request has been automatically failed because it uses a
deprecated version of `actions/upload-artifact: v1`. Learn more:
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
To maintain CI builds that typically succeed, let's cherry-pick this into Git for Windows' `main` branch.
=> Backport `linux32` CI fix from upstream Git

t/t5512-ls-remote.sh, t/t5551-http-fetch-smart.sh
This patch implements a work-around, basically for the sake of Git for Windows v2.46.2's CI build: The `macos-13` runner images still reference libcurl v8.10.0, which has a known flaw that breaks t5559.30. Let's detect this situation and skip that test case in that case.
While at it, also backport the work-around for a flaky test case (t5512.40 "helper with refspec capability fails gracefully").
This fixes https://github.com/git-for-windows/git/issues/5159.
=> ci: work around a problem with HTTP/2 vs libcurl v8.10.0

.gitignore, Documentation/git-backfill.txt, Documentation/technical/api-path-walk.txt, Makefile, builtin.h, builtin/backfill.c, command-list.txt, dir.c, dir.h, git.c, path-walk.c, path-walk.h, t/helper/test-path-walk.c, t/t5620-backfill.sh, t/t6601-path-walk.sh
This change introduces the `git backfill` command which uses the path walk API to download missing blobs in a blobless partial clone.
By downloading blobs that correspond to the same file path at the same time, we hope to maximize the potential benefits of delta compression against multiple versions.
These downloads occur in a configurable batch size, presenting a mechanism to perform "resumable" clones: `git clone --filter=blob:none` gets the commits and trees, then `git backfill` will download all missing blobs. If `git backfill` is interrupted partway through, it can be restarted and will redownload only the missing objects.
When combining blobless partial clones with sparse-checkout, `git backfill` will assume its `--sparse` option and download only the blobs within the …
=> Introduce 'git backfill' to get missing blobs in a partial clone

.gitignore, Documentation/config.txt, Documentation/config/survey.txt, Documentation/git-survey.txt, Makefile, builtin.h, builtin/survey.c, command-list.txt, git.c, t/t8100-git-survey.sh
This introduces `git survey` to Git for Windows ahead of upstream for the express purpose of getting the path-based analysis in the hands of more folks.
The inspiration of this builtin is [`git-sizer`](https://github.com/github/git-sizer), but since that command relies on `git cat-file --batch` to get the contents of objects, it has limits to how much information it can provide.
This is mostly a rewrite of the `git survey` builtin that was introduced into the `microsoft/git` fork in microsoft/git#667. That version had a lot more bells and whistles, including an analysis much closer to what `git-sizer` provides.
The biggest difference in this version is that this one is focused on using the path-walk API in order to visit batches of objects based on a common path. This allows identifying, …
=> Add experimental 'git survey' builtin

diff-lib.c, diff.c, diff.h, graph.c, line-log.c, log-tree.c, range-diff.c, t/t4211-line-log.sh
This fixes https://github.com/git-for-windows/git/issues/5185 by backporting https://github.com/gitgitgadget/git/pull/1806 (which, sadly, seems not to have made it into Git v2.47.0).
=> Fix `git log --graph -u` hangs

path-walk.c, t/t6601-path-walk.sh
When adding tree objects, we are very careful to avoid adding the same tree object more than once. There was one small gap in that logic, though: when adding a root tree object. Two refs can easily share the same root tree object, and we should still not add it more than once.
=> path-walk API: avoid adding a root tree more than once

builtin/gc.c, t/t7900-maintenance.sh, t/test-lib.sh
> This patch was sent upstream by Patrick. I'm contributing it to Git for Windows quickly to make sure it gets into microsoft/git, but also in advance of any potential 2.47.1.
It was reported on the mailing list that running `git maintenance start` immediately segfaults starting with b6c3f8e12c (builtin/maintenance: fix leak in `get_schedule_cmd()`, 2024-09-26). And indeed, this segfault is trivial to reproduce up to a point where one is scratching their head why we didn't catch this regression in our test suite.
The root cause of this error is `get_schedule_cmd()`, which does not populate the `out` parameter in all cases anymore starting with the mentioned commit. Callers do assume it to always be populated though and will e.g. call `strvec_split()` on the returned value, which will of …
=> builtin/gc: fix crash when running `git maintenance start`

builtin/survey.c
Currently, it defaults to 100, which is a bit excessive given that there are multiple tables with that maximum row count.
Let's default to 10 instead. It's easy enough to increase the limit via command-line or config.
=> survey: default to --top=10

path-walk.c
In the presence of many tags, the use of oid_array_lookup() can become extremely slow. We should rely upon the SEEN bit instead.
This affects the tag-peeling walk as well as the switch statement for adding the peeled object to the correct oid_array.
----
@derrickstolee found this while testing the 2.47.0.vfs.0.0 pre-release against a repo with many annotated tags.
This is a backport of https://github.com/microsoft/git/pull/695.
=> path-walk: improve path-walk speed with many tags

scalar.c
There was a typo in the configuration Scalar registers, which was missed by author and reviewer 🤦. No big harm done, let's just fix this in time for the next Git for Windows version.
=> fixup! scalar: enable path-walk during push via config

Makefile, builtin/credential-cache.c, compat/mingw.c, compat/mingw.h, t/meson.build, t/t0301-credential-cache.sh, t/unit-tests/u-mingw.c
I should probably add some tests for this.
=> credential-cache: handle ECONNREFUSED gracefully

compat/mingw.c
[`CreateFileW()` requires `FILE_FLAG_BACKUP_SEMANTICS` to create a directory handle](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew#directories) and errors out with `ERROR_ACCESS_DENIED` without this flag. Fall back to accessing Directory handles this way.
This fixes https://github.com/git-for-windows/git/issues/5068
=> mingw_open_existing: handle directories better

SECURITY.md
The `SECURITY.md` document mentions Git for Windows' snapshots and helpfully provides a link.
For almost eight years, Git for Windows' snapshots were hosted [on Azure Blobs](https://wingit.blob.core.windows.net/files/index.html).
As of a combination of PRs (https://github.com/git-for-windows/git-for-windows-automation/pull/109, https://github.com/git-for-windows/gfw-helper-github-app/pull/117), snapshots are not only now built and deployed via GitHub Actions instead of Azure Pipelines (and ARM64 artifacts are now included, too), they are also hosted [on GitHub](https://github.com/git-for-windows/git-snapshots/releases/), with the main page being hosted [on GitHub Pages](https://github.com/git-for-windows/git-snapshots/commits/gh-pages).
Therefore, the original link now redirects to a new …
=> SECURITY.md: use the new Git for Windows snapshots URL

compat/mingw.c
This fixes #5436. I've tried to write the commit message (6a994b2) in such a way that it would be suitable both here and upstream, but I do not know if I succeeded at that. As noted in the commit message, and in the issue, existing tests are able to detect the bug this is fixing, so at least for now I have not written any tests.
The code this modifies is also present upstream, but my understanding of the contribution guidelines is that I should open this PR here rather than submitting a patch to the Git mailing list, because the effect of this change is entirely Windows-specific. If this instead needs to be submitted to the mailing list, then I could try and do that. The change here is also rather simple, and I would certainly have no objection to it being integrated in some other way …
=> compat/mingw: rename the symlink, not the target

compat/win32/fscache.c, config.mak.uname
Most notably, this fixes https://github.com/git-for-windows/git/issues/5431, i.e. that the ARM64 flavor of Git for Windows does not use `/etc/gitconfig` by mistake, but `/clangarm64/etc/gitconfig` instead.
My original intention was to fix only that issue, but when I fired up a Git for Windows/ARM64 SDK and tried to build, I immediately ran into trouble, then noticed places where ARM64 was not yet handled, and one thing led to another and now it's a 6-patch PR instead of a single-patch one.
=> Some `clangarm64` fixes

README.md
As per https://github.com/git-for-windows/git/discussions/5473, Git for Windows' Google Group is shut down.
=> README: stop mentioning the Google Group

config.mak.uname
This reverts a mistake of mine: My change to introduce an "else ifeq" in https://github.com/git-for-windows/git/pull/5439 chain missed that there is [an `else` clause](https://github.com/dscho/git/blob/31963038164d1a2d78dc46225f8441e8c0fb07a8/config.mak.uname#L739-L742) that should be used for MINGW32 and MSys (to add large-address-awareness and use 32-bit `time_t`) but not for CLANGARM64 nor for MINGW64.
=> Re-enable MINGW32-specific compile options

CONTRIBUTING.md, README.md, SECURITY.md
This is a follow-up for https://github.com/git-for-windows/git-for-windows.github.io/pull/59.
=> Replace the superseded wiki URLs

.github/workflows/main.yml, Makefile, ci/install-dependencies.sh
I noticed that the CI builds of `shears/main` were failing, as well as the PR builds of #5586. The reasons are outside of Git for Windows, but the fixes need to be inside anyway.
=> Fix CI builds again

compat/mingw.c, environment.c, t/t0060-path-utils.sh
I encountered these issues that had hitherto escaped us [when I worked on letting the `ci-artifacts` workflow in git-sdk-arm64 also build Git and run the test suite](https://github.com/git-for-windows/git-sdk-arm64/pull/37) by way of validating the `minimal-sdk` artifact.
Mind, this PR does not only adjust a test case that was previously too fixated on x86_64. There are two real issues that this PR addresses and that were found via the test suite:
- When the environment variable `MSYSTEM` is not yet set, it now is set appropriately even on Windows/ARM64 (and the `PATH` is adjusted accordingly).
- The tree traversal limit designed to avoid stack overflows needed to be adjusted for the clangarm64 builds.
=> clangarm64: let the tests pass!

compat/mingw.c
Apparently my tests of https://github.com/git-for-windows/git/pull/5586 had been incomplete. This here patch is needed to let t0060.221 pass (where it verifies that `git.exe` sets `MSYSTEM` correctly if that environment variable has not yet been set): Simply reverse the order of the tests whether to set `MINGW64` or `CLANGARM64` to avoid using the former on Windows/ARM64 by mistake.
=> Fix t0060.221 on Windows/ARM64

.github/workflows/monitor-components.yml
curl recently started releasing rc versions, but we don't want to act on them, so there is no need to open issues about every rc version.
=> monitor-components: skip curl prereleases

ARCHITECTURE.md
We don't use the selfhosted runners anymore, drop the outdated paragraph describing that old setup.
=> stop mentioning the old selfhosted arm64 runner  setup

compat/mingw.c
The pattern `return errno = ..., -1;` is observed several times in `compat/mingw.c`. It has served us well over the years, but now clang starts complaining:
```
compat/mingw.c:723:24: error: possible misuse of comma operator here [-Werror,-Wcomma]
723 |                 return errno = ENOSYS, -1;
|                                      ^
```
See for example [this failing workflow run](https://github.com/git-for-windows/git-sdk-arm64/actions/runs/15457893907/job/43513458823#step:8:201).
Let's appease clang (and also reduce the use of the no longer common comma operator).
=> mingw: avoid the comma operator

http-push.c, http.h, imap-send.c, remote-curl.c
As of three weeks ago, every CI build of Git for Windows' ARM64 flavor of its SDK started failing (the first failed build is this [here](https://github.com/git-for-windows/git-sdk-arm64/actions/runs/17633130672/job/50104373185)).
I had mistaken this for a problem with `git/git` and therefore tried to fast-track (for some definition of "fast") the patch into `git/git`, but I had forgotten that I changed `git-sdk-arm64`'s `ci-artifacts` workflow [to build `git-for-windows/git` instead](https://github.com/git-for-windows/git-sdk-arm64/commit/1b7ec02e29ae3638cf93b603ad2f9a2248b0e85e) (because of the problems that needed to be fixed).
So let's integrate these patches into Git for Windows before they trickle in via a new Git version (which is [currently scheduled for November 17th, …
=> Fix `curl_easy_setopt()` parameter type problem, again
